### ISSUE TITLE
can't read/find the journals 

### ISSUE THREAD

**Issue by GALDART** [jixxed/ed-odyssey-materials-helper#1]
Is it necessary to install in a specific folder? he cannot read my journals.

**Comment by jixxed** [comment]
it reads the files from %userprofile%\Saved Games\Frontier Developments\Elite Dangerous

Do you have another location configured?
What game client/OS are you using?

**Comment by jixxed** [comment]
this link describes a similar problem: https://forums.frontier.co.uk/threads/cannot-find-player-journal-log.405782/

You might need to create the folder yourself or set correct permissions. When the game creates journal files in the specified location, the application will start working.

your install location should not be a factor.

**Comment by GALDART** [comment]
my game is from steam, I'm using windows 10 version 20h2, my game is installed in the default folder and the journals are in the default folder too (%userprofile%\Saved Games\Frontier Developments\Elite Dangerous), other programs like EDMC, EDDDiscovery and EDEngineer read journals normally.

when opening ed-odyssey-materials-helper everything is blank, as if he was not finding the journals. 

![Captura de tela 2021-06-08 160359](https://user-images.githubusercontent.com/38081436/121245609-95cf0280-c876-11eb-9a85-c6010870d384.png)
![Captura de tela 2021-06-08 160148](https://user-images.githubusercontent.com/38081436/121245615-97002f80-c876-11eb-80a9-1d9b3fafe40d.png)

**Comment by jixxed** [comment]
It reads only the latest Journal file. Did you happen to run Horizons last?

**Comment by GALDART** [comment]
> ‎Ele lê apenas o último arquivo do Jornal. Por acaso você executou horizons por último?‎

i have just logged in odyssey mode, i just closed the game and reopened to generate a new journal, and the program remains blank.

if you need more specific information to try to find out what is going on i can provide it. 

![Captura de tela 2021-06-08 195125](https://user-images.githubusercontent.com/38081436/121267970-667abe80-c893-11eb-895e-667493269997.png)

**Comment by GALDART** [comment]
ok, i discovered the problem, it was the language of my game, i play in portuguese, i changed the language to english and it detected the materials.

**Comment by jixxed** [comment]
verified the issue. fixed in the 1.7 version!

**Comment by jasehuss** [comment]
I have this same issue, I have 1.25 installed, win 10. Game is installed on D: default folder. my Journals are definately located on C: drive at the path shown at the bottom of the helper. 
![image](https://user-images.githubusercontent.com/78591880/126143468-bafa2f27-be16-4a30-b378-33a8bb15fcac.png)

**Comment by jixxed** [comment]
@jasehuss can you create a new issue for this? this one is closed. Please share you latest journal after logging into elite and starting the application. also share the backpack.json and shiplocker.json files.
