### ISSUE TITLE
feature request: personal filter

### ISSUE THREAD

**Issue by feiercrack** [jixxed/ed-odyssey-materials-helper#10]
would be fantastic if u can integrate an filter with what we can select just our personally needs to farm

because there are sometimes mission related items, like the Lazarus etc on an farming tour...

and we need an filter to separate  (hide / unhide) an selection  from the Grade Upgrading - and - the Engineer Modification Slots
because i think we first need all to do the Grades, collecting for that, and after that do the Engineer Mods Slot extension

**Comment by jixxed** [comment]
I've implemented preference storage in the latest version. it just saves the screen position for now, but it will cater to making a favourites filter possible.

**Comment by jixxed** [comment]
1.17 now has favourites selection and filtering
