### ISSUE TITLE
Failed to launch JVM error after upgrading to 1.99

### ISSUE THREAD

**Issue by gunr2171** [jixxed/ed-odyssey-materials-helper#100]
I was previously on 1.98. Just now I launched the application which auto-downloaded and applied the 1.99 update. After the pac-man animation was done, I get the following:

![image](https://user-images.githubusercontent.com/8290105/200404362-6f1387c8-38bc-4874-abca-6d30b33e9adb.png)

And then pressing Ok:

![image](https://user-images.githubusercontent.com/8290105/200404434-97f2fb3c-6134-45a7-b1ff-84b38b6085f6.png)

After closing the second window the process exits. Relaunching the app does another update check, then repeats the error windows.

I'm running Windows 11. I do have `java` on the command line, but it's due to (hopefully) an unrelated feature in Visual Studio for Android development.

I know 1.99 is installed because looking at the Properties -> Details of `"C:\Users\[MyUser]\AppData\Local\Elite Dangerous Odyssey Materials Helper Launcher\program\Elite Dangerous Odyssey Materials Helper.exe"` says 1.99.

I see there's a log folder, but the only file (`edomh.log`) just has 

```
#logback.classic pattern: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{35} - %msg%n
```

as the contents.

If there's something else you want me to try (I can uninstall and install fresh if you tell me where my persistent data is stored) please let me know.

**Comment by gunr2171** [comment]
Some additional info: just downloaded the 1.98 and 1.99 portables, those both launch just fine, so it's something with the installed version. Hopefully not just _my_ install.

**Comment by jixxed** [comment]
you can remove the program folder. then pacman will download the latest version again. it looks like something went wrong during the update.

**Comment by gunr2171** [comment]
I renamed the `program` folder to `program-bak`, relaunched the application from the start menu, the pacman animation played and downloaded the 1.99 version, and then the application launched correctly.

So yeah, you're right that something was up with my instance. Sorry that I didn't try this before, but I didn't know which folder kept my settings and configurations.

**Comment by jixxed** [comment]
your personal settings are located in %localappdata%\odyssey-materials-helper and will survive even the removal of the application.
