### ISSUE TITLE
Request: Separate Augmented Reality for trading with Barmen

### ISSUE THREAD

**Issue by paladinkolovrat** [jixxed/ed-odyssey-materials-helper#102]
I usually download all data and AR is not needed for me in such case, but AR for trading with Barmen will be a good addition.

**Comment by jixxed** [comment]
this is not possible for selling materials, the list is too long and performance becomes an issue. It might eventually get implemented for the trading part only.

**Comment by paladinkolovrat** [comment]
Tbh, I'm ok with the performance loss during data selling. It's much faster than checking every data material with the table of usefulness, anyway.

Will it possible to add this feature? Just warn CMDRs with popup message that the function will hit the performance, that's all.

**Comment by jixxed** [comment]
possible yes, but will not build it. will take over 100 hours to develop and then works poorly. but if anyone else feels like building it, they can try.
