### ISSUE TITLE
Caustic crystal is missed

### ISSUE THREAD

**Issue by paladinkolovrat** [jixxed/ed-odyssey-materials-helper#105]
Caustic shard exists as regular materail.
But there's exist rare Caustic crystal, maximum 100 units.

**Comment by paladinkolovrat** [comment]
Bit from journal:
{ "timestamp":"2022-11-30T01:42:44Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"tg_causticcrystal", "Name_Localised":"Едкий кристалл", "Count":3 }

**Comment by paladinkolovrat** [comment]
Added in 2.3. Closed.

**Comment by jixxed** [comment]
I have not yet seen this myself or a screenshot or the right hand panel, so I am not sure of the rarity

**Comment by paladinkolovrat** [comment]
This material is 200 unit maximum now.
It seems Fdev are still in process of adjusting new materials.
PS. Description says that this material is [very] rare. In Russian, at least.
