### ISSUE TITLE
1x(10-19) numbers don't fit the Horizon material bar

### ISSUE THREAD

**Issue by paladinkolovrat** [jixxed/ed-odyssey-materials-helper#107]
When 1x(10-19) units of material are collected(green part) or left to be collected for maximum(red part) - these numbers don't fit the bar.
See the screenshot:
https://cdn.discordapp.com/attachments/788743092261355531/1047560603394375710/image.png

**Comment by jixxed** [comment]
thanks. there is already a minimum width for the colored bars to solve this specific issue, but I guess this needs to be increased a little bit more.

**Comment by jixxed** [comment]
fixed
