### ISSUE TITLE
Feature request: Hide relevant materials & zero inventory

### ISSUE THREAD

**Issue by DaftMav** [jixxed/ed-odyssey-materials-helper#11]
Similarly to how you can hide irrelevant materials, I'd like to see an option to hide relevant materials i.e. show only the trash materials. Adding to that with a checkbox that hides zero inventory and you'd get a nice list of stuff to sell. Either that or a combined option to only show "stuff to sell".

Thanks for this new tool! :)

**Comment by jixxed** [comment]
new sorting and filtering options added in 1.14!
