### ISSUE TITLE
Caustic shards and crystals are 200 units of capacity now.

### ISSUE THREAD

**Issue by paladinkolovrat** [jixxed/ed-odyssey-materials-helper#115]
As title says.

**Comment by jixxed** [comment]
can you add a screenshot?

**Comment by paladinkolovrat** [comment]
Sure:
https://cdn.discordapp.com/attachments/788743092261355531/1049432741139202139/1.jpg
Translation:
Crystals 24/200
Shards 200/200

**Comment by jixxed** [comment]
I can't see the grades in this image. I need to see the complete thing, so I know if I need to modify a grade or add an override for it.

**Comment by paladinkolovrat** [comment]
Shards are the 2nd grade (2 leafs icon) and Crystals are the 4th grade (4 leafs icon). The thing is that these materials are 200 units max each.
In this case, grade doesn't mean the max capacity of the material, but only rarity. Strange but well.

**Comment by jixxed** [comment]
updated in 2.5
