### ISSUE TITLE
Exporting to CSV readability

### ISSUE THREAD

**Issue by bWildcard** [jixxed/ed-odyssey-materials-helper#118]
So currently when exporting to CSV everything is combinded into a single column, it would be much easier to read if it was as follows

Materials (First single column)   |   Relevant (Single Column)   |  Ammount (single column two sources)
List Down                                       List down (yes / No)             S#, FC#
Alphabetically
Assests First
Goods Second
Then data

Currently its all mashed together, with the toggle option to ignore materials for already unlocked engineers to now sort as Irrelevant 

Thus making sorting and there by selling easy, as its already sorted for us. This way when we go to sell at a bar we can easily see whats to sell as it appears in the bartender menu.

It could also be that Fdev cant sort shit correctly either, For instance in may game Biological Samples appear After C, genetic repair meds appear after T, and so on

**Comment by jixxed** [comment]
are you aware there is also a human readable xls version available to save?
