### ISSUE TITLE
EDOMH Not Opening, Giving me "Child Process exited with code 1"

### ISSUE THREAD

**Issue by CWSurpris3** [jixxed/ed-odyssey-materials-helper#119]
Exactly what the title says. I relaunched the setup and tried repairing it, but no luck. Should I make a clean install, just uninstalling from control panel and then reinstalling the setup? 

If need be I can attach what the error window looked like.

**Comment by jixxed** [comment]
check if there is already a running process in taskmanager and kill it

**Comment by CWSurpris3** [comment]
There isn't anything related to EDOMH, what process/service am I looking for exactly?

**Comment by jixxed** [comment]
Elite dangerous odyssey materials helper. you can also try a reboot.

**Comment by CWSurpris3** [comment]
Looks like the problem was just a one off. Have been using it the last couple of days and not had any issue with the same error. Thanks :)
