### ISSUE TITLE
Overlay improvement - Mission Boards

### ISSUE THREAD

**Issue by leonardofelin** [jixxed/ed-odyssey-materials-helper#126]
Hi, any chance the overlay could read the mission boards and flag missions with materials in the wishlist, just like when downloading from data ports?

For this to work, player would need to select "Materials" from the filter list.

**Comment by jixxed** [comment]
It has been requested several times. This would be difficult to implement and most definitely have bad performance. I like to keep the UX on a high level and this would tank it. there could be something if fdev would write the missions information to a file, but not to the degree of the dataports. you would need a supercomputer to do image recognition and OCR at 60fps. (for the dataport it runs at 0-1fps)
