### ISSUE TITLE
Feature request: open last opened tab and other tabs features

### ISSUE THREAD

**Issue by riwarek** [jixxed/ed-odyssey-materials-helper#128]
1. If it is possible, please add feature your app will open on last used tab before closure.
2. Also please add feature of hide tabs, eg I never used "bartender", "loadout editor" and other from Odyssey.
3. It would be also useful to combine the same tabs trom Horizon in Oddysey. Then I would have eg. whislist with everything without need of switch between releases.

**Comment by OzDruiD** [comment]
For me . I prefer these tabs and separation, so if these feattures are implemented, should be optional \ toggle.
2nd .. I will make a seperate feature request, but really really really want the 'trade down' type caculation on materials.

**Comment by jixxed** [comment]
1. this can be added
2. don't really feel much for this feature. there are not that many tabs and you can simply NOT click them.
3. it's more of an on foot and ships level of separation. not everyone has odyssey and would be interested in that content. also the tabs would become too busy. A player would usually be focused on either shipbuilding or suitbuilding

**Comment by jixxed** [comment]
tab member berries have been applied
