### ISSUE TITLE
Microelectrode trading points are wrong

### ISSUE THREAD

**Issue by charlesyu08** [jixxed/ed-odyssey-materials-helper#13]
![Elite Dangerous Screenshot 2021 06 15 - 18 16 06 27](https://user-images.githubusercontent.com/5238533/122096048-04c3d280-ce06-11eb-82ea-6f1ee7bdb63c.png)
![image](https://user-images.githubusercontent.com/5238533/122096069-09888680-ce06-11eb-956b-645487ee9965.png)
Should be 16 / 9

**Comment by Patsch78** [comment]
It seems that all the Micro* are mixed up a bit.

Micro Supercapacitor has the points of Micro Transformer
Micro Transformer has the points of Microelectrode
Microelectrode has the points of Micro Supercapacitor

**Comment by jixxed** [comment]
thanks for the report. indeed wrongly copied over due to two of them having a space.

**Comment by jixxed** [comment]
fixed in 1.18!
