### ISSUE TITLE
MaxSecure - Trojan.Malware.300983.susgen

### ISSUE THREAD

**Issue by alexpebody** [jixxed/ed-odyssey-materials-helper#131]
Hello, Sorry, but this is mistake or inside of script some strange instruction...? Thank you. [https://www.virustotal.com/gui/file/3b6f6c464ec4095d97fb8178a6dab55243a4dc3ef9450e442bb9046bc12ae1ad](url)

**Comment by jixxed** [comment]
False positive

**Comment by alexpebody** [comment]
> False positive

Thx
