### ISSUE TITLE
German Translation incorrect

### ISSUE THREAD

**Issue by NecroVortex** [jixxed/ed-odyssey-materials-helper#139]
Hey jixxed,

the Elite Dangerous Odyssey Materials Helper is a good additional support besides the ED Engineer. I think EDOMH is even better. Unfortunately, the German translation is somewhat flawed.

I would be happy to help you translate the words correctly if you wish. Let me know briefly and if the whole thing runs via a file, let me know which one it is or give it to me. I would then try to do it as quickly as possible, depending on my own time.

Regards

**Comment by jixxed** [comment]
All locales are in https://github.com/jixxed/ed-odyssey-materials-helper/tree/master/application/src/main/resources/locale
There have been some people on the discord saying they wanted to do the localizations, but not much ever came of it. only fixes for a couple items. Feel free to make a pull request with your changes. I always try to keep changes at the end of the file so it will be easier to maintain in the future. There is someone that keeps Russian up to date pretty consistently.

**Comment by NecroVortex** [comment]
Thanks for the info. I'll take a look at the whole thing and write to you here when I've finished it. Of course it will take a bit of time, but it will help. 😄

**Comment by jixxed** [comment]
Someone has improved German translations. any updates can be submitted though PR's
