### ISSUE TITLE
feature request - dark mode

### ISSUE THREAD

**Issue by Patsch78** [jixxed/ed-odyssey-materials-helper#14]
It would be really nice to have a dark mode switch. ed-odyssey-materials-helper is relatively bright especially on a multi monitor setup when you are on a sneaky on foot mission in a dark settlement.

cheers and thanks
patsch

**Comment by jixxed** [comment]
feature added to the wishlist! And thanks for the donation :D

**Comment by Patsch78** [comment]
You're welcome, I really like your tool :-)

**Comment by jixxed** [comment]
implemented in 1.18!
