### ISSUE TITLE
Sync between 2 machines and prefs files

### ISSUE THREAD

**Issue by fatlazycat** [jixxed/ed-odyssey-materials-helper#140]
Hi will the portable version allow me to run this from 2 machines if I sync via one drive ? i.e. will the prefs / wish list be stored in this directory ?

If so is it possible to move from the msi version ? i.e. where would the prefs that need to be moved.

Thanks for the amazing app !

**Comment by jixxed** [comment]
the msi is an auto updater for the portable version and the recommended way to use the app so you are always on the most recent version. all it does is download the latest portable version for you if updates are required and then launch it. you can potentially run on multiple machines, but not simultaneously. the app only reads the files on launch and after that only writes to them, so multiple instances at the same time would cause issues.
