### ISSUE TITLE
No longer counts Caustic Tissue Samples

### ISSUE THREAD

**Issue by FryaDuck** [jixxed/ed-odyssey-materials-helper#149]
With U15 EDOMH no longer shows caustic tissue sample count (whether in ship inventory or fleet carrier inventory)
![sample](https://github.com/jixxed/ed-odyssey-materials-helper/assets/87042542/d246f5e8-bb52-4d4d-b0c4-813835398532)
![edomh](https://github.com/jixxed/ed-odyssey-materials-helper/assets/87042542/8322ec29-341f-4120-b086-3339dc3c0420)

**Comment by jixxed** [comment]
Shows up fine here, perhaps a logging delay issue?

**Comment by FryaDuck** [comment]
Sorry jixxed, my error. Didn't register the app with my frontier account (just bought a fleet carrier). Still if people don't do that they'll have the same problem

**Comment by jixxed** [comment]
the FC icons are now hidden if you never registered the API.
