### ISSUE TITLE
[Suggestion] Update Notification improvement

### ISSUE THREAD

**Issue by Fixitman333** [jixxed/ed-odyssey-materials-helper#150]
If there is an update to this application, it produces a popup at launch. The popup is always hidden behind the ED window. Clicking the continue button on the popup is required to continue launching the application. It is not obvious that the popup is there until the application fails to show on my other monitor.

It would be helpful to place a timer on the continue button, or make it possible to completely suppress it. A link in the "About" section of the application would make it easy to see release notes at any time.

**Comment by jixxed** [comment]
It's important that people do the update, so the nag screen has to stay. I can probably give it an always on top setting. If you install the autoupdater and launch the application through that, you will never see this window.

**Comment by Fixitman333** [comment]
The first manual installer I used was **Elite.Dangerous.Odyssey.Materials.Helper.Auto.Updater-2.21.msi**. I installed on top of that with **Elite.Dangerous.Odyssey.Materials.Helper.Auto.Updater-2.22.msi** last week. I launch the application with a windows shortcut to **Elite Dangerous Odyssey Materials Helper Launcher.exe**. I thought that was the autoupdater, but the application is obviously not auto-updating. I see nothing regarding "auto" anywhere in the app's install location.

Please provide specific instructions on GitHub regarding how to install and use the autoupdater.  The linked videos make no mention of the autoupdater.

**Comment by jixxed** [comment]
the msi file is correct and **Elite Dangerous Odyssey Materials Helper Launcher.exe** is the correct executable to launch. It should give you a pacman program that downloads the latest version for you and then launches the application. Do you see that window? If you do not, you are launching the app directly and not through the launcher. You can see your current version in the **About** section of the app or in the **what's new** section on first launch after an update. The auto updater itself will not update with every release. (it also doesn't change)

**Comment by Fixitman333** [comment]
The pacman program does launch first, but it apparently doesn't work. I suspect it may be blocked by my firewall. I've looked through my firewall rule-set, but I don't see "pacman" listed. What else should I look for?

**Comment by jixxed** [comment]
the pacman program is **Elite Dangerous Odyssey Materials Helper Launcher.exe**
the app itself is **Elite Dangerous Odyssey Materials Helper.exe**

**Comment by jixxed** [comment]
Clicking continue does nothing. The update happens with the pacman program. It sounds like that it is actually updating the program, but when it launches and does a check, it fails to identify that it is on the latest version. What does it show in the About section of the app? perhaps failing to fetch the latest version results in the popup being shown.

**Comment by Fixitman333** [comment]
I know the about section currently shows version 2.25. I'll check the log when I get home this evening (4-5 hours from now).

**Comment by Fixitman333** [comment]
I don't have a folder named **Elite Dangerous Odyssey Materials Helper Launcher\log** within **C:\Users\USER\AppData\Local**. There is a folder named **odyssey-materials-helper**, but it doesn't appear to contain any log files.

**Comment by jixxed** [comment]
No, if you changed the install location, that's where the log file is. can you share it?

**Comment by Fixitman333** [comment]
Notes:
It only appears to have entries from my last play session, which was last night.
All instances of my user ID have been replaced with "USER".
I don't own a fleet carrier on any of my 4 commanders at this time.
[edomh.log](https://github.com/jixxed/ed-odyssey-materials-helper/files/11469492/edomh.log)

**Comment by jixxed** [comment]
there's nothing in the log so it is strange you still got a download notification. I got a potential fix, but since there is no error it will probably not work.

**Comment by Fixitman333** [comment]
I only get the update notification after an update is released. The log from the last release has already been overwritten since then. I'll uninstall, then install an older version. That will either fix the issue, or produce the notification again. If it produces the notification, I'll post the new log file. If it doesn't, I'll close this issue.

**Comment by jixxed** [comment]
perhaps it is your security software then that is initially blocking outgoing connections?

**Comment by Fixitman333** [comment]
I think I know what's happening now. I initially installed version 2.21 when that was the latest. When version 2.22 was released, I received the "What's new & privacy policy" window. I thought that was a notification to update, so I clicked "Close application", and downloaded version 2.22.  Shortly after that, I started trying to get EDOMH to auto-launch and close using [MinEDLauncher](https://github.com/rfvgyhn/min-ed-launcher). At one point, I switched to bypassing the EDOMH launcher, but nothing worked. It would launch either way, but auto-closing wouldn't work. By the time I gave up, EDOMH 2.25 was released, and I got the "What's new..." window again.

Now I understand how "Auto update" works. It automatically updates the entire application, not just the collection source data. Will clicking "Accept & Continue" prevent that window from showing after future updates?

**Comment by jixxed** [comment]
No that window always shows after an update to inform about important changes and privacy policy changes. Although the privacy policy usually doesn't change so the button just says Continue. Always a good idea to read the latest changes so you are aware of the latest features.

**Comment by Fixitman333** [comment]
The simplest solution is to launch EDOMH first, wait for it to load, then launch everything else. After playing ED for so many years, I'm used to workarounds, and this is an easy one.

Thanks for taking the time to explain how EDOMH auto-update works.
