### ISSUE TITLE
New material in P15

### ISSUE THREAD

**Issue by paladinkolovrat** [jixxed/ed-odyssey-materials-helper#158]
Revenants are dropping Tactical Core Chip, 2 grade, 100 units cap

**Comment by jixxed** [comment]
check cap after relog

**Comment by jixxed** [comment]
and add a screenshot

**Comment by jixxed** [comment]
{
  "language": "English/UK",
  "name": "unknowncorechip",
  "localized": "Tactical Core Chip"
}
{
  "language": "Russian/RU",
  "name": "unknowncorechip",
  "localized": "Чип тактического ядра"
}
{
  "language": "French/FR",
  "name": "unknowncorechip",
  "localized": "Puce tactique principale"
}
{
  "language": "Spanish/ES",
  "name": "unknowncorechip",
  "localized": "Chip de núcleo táctico"
}

**Comment by paladinkolovrat** [comment]
Yes, I was surprised too and tried to relog and restart the game - nothing changed.
[https://cdn.discordapp.com/attachments/788743092261355531/1107018426175725761/image.png](url)

**Comment by jixxed** [comment]
perhaps a restart is required, the other materials also started on 100, but have since changed. I am sure this one will too.

**Comment by paladinkolovrat** [comment]
> perhaps a restart is required
As I said in previous message - I restarted the game.
The screenshot is from the restarted game.

**Comment by jixxed** [comment]
apologies, didn't read that correctly. still going with 250 for now, unless it doesn't change for a while.

**Comment by paladinkolovrat** [comment]
No problem, I had similar issue with Membrane Residue yesterday, but its mat cap was updated instantly.
This case, imo, is different: low spawn rate tells that the Chip is not a 2nd grade material.
