### ISSUE TITLE
Vertical scrolling with mousewheel is not smooth

### ISSUE THREAD

**Issue by tbayart** [jixxed/ed-odyssey-materials-helper#159]
When scrolling with mousewheel, the list scrolls sometimes too much.
  The best example is with the **Materials** list.

  Here i'm on top of the list, bottom item is **Cast fossil**, notice the vertical scroll caret position :
![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/5262768/2b1cfd24-7e08-4a89-b8f4-6ad91fa26a4c)  

  I scroll down one step with mousewheel  
the vertical scroll caret position downed too much and the top item is **Nutritional Concentrate** :
![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/5262768/763297e9-a034-40f2-af09-f6699af56cf0)  

  I scrolled up by draging the vertical scroll caret to see both previous items to check the gap but there is more than one screen size.
I mean, the missed items does not fit in one screen.

**Comment by jixxed** [comment]
Fix added in 2.27

**Comment by tbayart** [comment]
> Fix added in 2.27

Tested and validated, good job 👍
