### ISSUE TITLE
Tooltip is taller than screen

### ISSUE THREAD

**Issue by tbayart** [jixxed/ed-odyssey-materials-helper#160]
Screenshot below shows Manufacturing Instructions tooltip.
There is too much information making the tooltip taller than the screen height and no scrollbar to see useful information at the bottom.

![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/5262768/267a5938-c427-4714-bea9-a68281e04be3)

**Comment by jixxed** [comment]
what resolution are you using?

**Comment by tbayart** [comment]
My screen is full HD 1920x1080

**Comment by jixxed** [comment]
placed clickable blueprints into collapsible panels in 2.27 (same as horizons materials)
Please close the issue if this fixed it for you

**Comment by tbayart** [comment]
Yeah, good job, + you also put blueprints inline instead of one per line which allow some spce saving

![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/5262768/2cec4d02-7d33-44dc-9247-400c8e605c03)
