### ISSUE TITLE
[Suggestion] Setting "Expanded recipies in the material descriptions by default"

### ISSUE THREAD

**Issue by paladinkolovrat** [jixxed/ed-odyssey-materials-helper#161]
It was useful for me that the recipies where material is used are shown once you move the cursor on the material.
Now, I need to extra click at least once just to make sure that the material is ok (or not ok) for me.

Could you please add an option to automatically expand the list of recipies?

https://cdn.discordapp.com/attachments/788743092261355531/1114304641568620634/image.png

**Comment by jixxed** [comment]
added for the next release under Settings - general

**Comment by paladinkolovrat** [comment]
Cool!
Thank you!
