### ISSUE TITLE
When pinning application to Win 10 taskbar the EDOM logo become a white sheet

### ISSUE THREAD

**Issue by RoscoeDark** [jixxed/ed-odyssey-materials-helper#165]
Version 2.27 was ok but from V 2.28,  Logo EDOM is switching to a white sheet. Unpinning the application restore the original Logo which is just a bit boring. As the Shortcut is lying on the Windows desk under the main screen when ED ODYSSEY is launched. So pinning the appli is more comfortable.

**Comment by jixxed** [comment]
You can pin the launcher instead of the application itself. the launcher does not get updated with new versions.

**Comment by RoscoeDark** [comment]
Thank's but when doing that, seems like EDOM is not tunning properly = Overlay doe'nt work at all. Reboot and launching by the Desktop Shortcup, fixed the issue. But pinning still unusable even by pinning the launcher.

**Comment by jixxed** [comment]
that makes no sense at all. the way you launch the app doesn't matter.
