### ISSUE TITLE
Duplicate engineer wishlisting

### ISSUE THREAD

**Issue by cgiAlexis** [jixxed/ed-odyssey-materials-helper#17]
# Issue
It's possible to add duplicate engineer entries to the Wishlist which will increase how many materials a user will be guided to harvest

## Contributing factors
1. The program doesn't check to see if an engineer unlock recipe of the same type has been added
2. The user has no visual feedback when selecting "Add to wish list"

## Solutions
1. Detect if the engineer unlock recipe is in the wishlist
2. Make the button non-interactive. Grey out the text or have it switch to "On wish list"

## Replication
1. Switch to Engineer Unlocks on sidebar
2. Switch to Wishlist in main window
3. Select an engineer and select "Add to wish list"
4. Repeat as many times as you wish

![image](https://user-images.githubusercontent.com/7907361/124014898-01227500-d9dc-11eb-86a9-d738d8392c4f.png)

_**This is an amazing program, thanks for your work!**_

**Comment by jixxed** [comment]
Thank you Alexis for your report and donation!
The implementation for the wishlist is very basic as it is the first iteration, to get some feedback from the users to see what they would like to see changed.
I agree that the button interaction can be a bit better. I will definitely have a look into that.
I do believe the recipe should be able to be added multiple times, as it depends on you playstyle. You could be collecting materials for a friend.

**Comment by cgiAlexis** [comment]
Roger that! The priority on this I think should be lower than your more intrinsic data integrity preservation issues;

What if you had a visual feedback in terms of a counter next to "Add to wishlist" that showed how many times it had already been added if it already existed? Similar to numbered icons on mobile launchers?

![tkGiT.jpg](https://user-images.githubusercontent.com/7907361/124031212-f2918900-d9ee-11eb-8d16-363d154a4597.jpg)

And maybe a visual feedback when someone hits the button like a colour change or animated "pop"?

![1_WB5Z5ZbBw_y8jvtlNoyxkQ.gif](https://user-images.githubusercontent.com/7907361/124031412-2ff61680-d9ef-11eb-82f1-51f75ff30415.gif)

https://medium.com/@lnatale/storytelling-with-mini-animations-acc3bda04c4d

Hope this clarifies, many thanks!

**Comment by jixxed** [comment]
several improvements have been made in 1.22!
