### ISSUE TITLE
App will not authenticate with Frontier API

### ISSUE THREAD

**Issue by Razwerkz** [jixxed/ed-odyssey-materials-helper#177]
This notification will appear shortly after the app update check.  No auth prompt is shown, and the app's main window becomes unresponsive.
![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/9700289/83aa2e9a-8237-4cea-a75c-7fe2e921548a)

**Comment by jixxed** [comment]
You need to enter settings and connect again. Frontier requires a new login every 30 days. If the app hangs for indefinitely, can you share your latest journal? You can DM it over discord if you like it to be private. If your latest journal has a lot of entries, loading can take a bit longer.

**Comment by Razwerkz** [comment]
Ah, I found out what happened.  The app window was not unresponsive; the actual app window was out of screen bounds (I recently lost one of my displays).  I should be able to get into the settings fine now.
