### ISSUE TITLE
French translation not very accurate

### ISSUE THREAD

**Issue by jfjago** [jixxed/ed-odyssey-materials-helper#183]
Some are very funny, for exemple Railgun is translated as pistolet de chemin de fer (gun for railroad) 
I can contribute to correct some translation if you wish, just telle me how I can do it

**Comment by jixxed** [comment]
Thank you for looking into this. Unfortunately Google is my only French friend.
you can find the locale files here:
https://github.com/jixxed/ed-odyssey-materials-helper/tree/master/application/src/main/resources/locale

Please do not reorder the files, new additions are always added to the end. So it is also easy for translators to maintain it.
You can fork the repository and create a pull request when you are done.

**Comment by jixxed** [comment]
there was another PR for French translations, but was never fixed and started to get merge conflict, so it was closed.
you can find it here if it helps: 
https://github.com/jixxed/ed-odyssey-materials-helper/pull/162
