### ISSUE TITLE
Problem: Materials info is difficult to read because it's at the same screen position as the team member(s) info

### ISSUE THREAD

**Issue by cyberbofh** [jixxed/ed-odyssey-materials-helper#189]
Problem:
When doing ground missions in a team, the helpful materials info is difficult to read because it's at the same screen position as the team member(s) info

Idea:
Make it so, that materials info is display at a different position on the screen
Right side, instead of current left side?

see attached screenshots of problem:
![2023-08-15_02-05-56](https://github.com/jixxed/ed-odyssey-materials-helper/assets/23364119/166b9aa9-1f5e-4d58-97cd-982407d928c5)
![2023-08-15_02-02-00](https://github.com/jixxed/ed-odyssey-materials-helper/assets/23364119/f605bcbe-3588-4800-97c1-38a544b8d077)

**Comment by jixxed** [comment]
This is not an EDOMH overlay
