### ISSUE TITLE
Unknown material - sabotagedcomponent

### ISSUE THREAD

**Issue by Epaphus** [jixxed/ed-odyssey-materials-helper#204]
Hi,

I keep getting a pop up very few minutes with unknown material detected "sabotagedcomponent" please report.
I suspect it's because I saw "Contaminated Spire Refinery Compound" on the bartender list after update 17 and setup a buy order for it.

Regards

Epaphus

![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/720274/dcf7eaac-5a3c-4749-8020-fef759e4357b)

**Comment by jixxed** [comment]
thnx for reporting. was waiting for this one. will add in the next release.
