### ISSUE TITLE
Failed to import EDSY wishlist

### ISSUE THREAD

**Issue by Jibsman** [jixxed/ed-odyssey-materials-helper#207]
Using my Asp Explorer as a model, I am trying to export the build into EDOMH.  I have used this before and it worked fine.
Now I get a beep and "Failed to Import EDSY wishlist. Failed to parse deeplink" (see bottom right of attached screenshot.

I am in Coriolis, not EDSY. Not sure why this is happening?

EDOMH Version: 2.4.1
Coriolis Version: [3.0.1 - 2023-07-27](https://github.com/EDCD/coriolis)
Do I have the wrong version? There are several out there now...

**Comment by jixxed** [comment]
Coriolis implementation incomplete and unsupported atm.
