### ISSUE TITLE
[Question] Is there any plan to implement Coriolis support?

### ISSUE THREAD

**Issue by shanel262** [jixxed/ed-odyssey-materials-helper#218]
I've been loving EDOMH (especially the shortest route to engineers feature) but all my builds are in Coriolis as I'm not a fan of the EDSY UI. 

Is there any plan to implement support for Coriolis imports like EDEngineer does? 

Thanks for the awesome tool!

**Comment by jixxed** [comment]
Support is already present but disabled. See also my comment on the Coriolis issue.

**Comment by shanel262** [comment]
Gotcha, thanks for the reply!
