### ISSUE TITLE
[Build Suggestion] Use fixed JavaFX versions

### ISSUE THREAD

**Issue by colin-heffernan** [jixxed/ed-odyssey-materials-helper#219]
Both the bootstrap and the application use a range of versions for JavaFX (and ControlFX for the application). This can potentially break builds. Shouldn't the versions be fixed instead to make builds deterministic, as is the case with all other dependencies? (I could probably submit a PR for this, if you'd like.)

**Comment by jixxed** [comment]
you are correct. not a real big issue though, but better to be specific. feel free to create a PR for it.

**Comment by colin-heffernan** [comment]
This seems to be resolved as of 2.45, so I'm closing the issue.
