### ISSUE TITLE
Unable to see Engineers for Stowed Reloading

### ISSUE THREAD

**Issue by FryaDuck** [jixxed/ed-odyssey-materials-helper#22]
![Capture](https://user-images.githubusercontent.com/87042542/124666452-6c46dc80-def1-11eb-91b9-d8d9ac4e97af.JPG)
 Doesn't matter if I resize or maximise the addon I can't see the engineers for Stowed Reloading (see image)

**Comment by jixxed** [comment]
can you share your resolution or a full picture of the application?

**Comment by kblinn2712** [comment]
Having a similar issue with Audio Masking not showing the Add to wishlist - possibly a few other weapon modules towards the top of that list.

**Comment by kblinn2712** [comment]
<img width="960" alt="2021-07-06" src="https://user-images.githubusercontent.com/87042909/124667533-8646d780-de7d-11eb-9efb-168dc7f84bb0.png">
<img width="960" alt="2021-07-06 (1)" src="https://user-images.githubusercontent.com/87042909/124667536-86df6e00-de7d-11eb-9b57-3eaf539434e1.png">

**Comment by jixxed** [comment]
you are using it at a lower size than it was originally designed for which is 1920x1080. I will see if I can make the menu scrollable though.

**Comment by jixxed** [comment]
fixed in 1.22!

**Comment by kblinn2712** [comment]
Thank you.

**Comment by FryaDuck** [comment]
Thanks jixxed
