### ISSUE TITLE
Good work 

### ISSUE THREAD

**Issue by maidenhunter** [jixxed/ed-odyssey-materials-helper#23]
Can this be configured for multiple accounts?

**Comment by jixxed** [comment]
yes, will look into this for a future version

**Comment by jixxed** [comment]
there are some caveats to consider with this feature. If running multiple clients side by side, they will both write to the same shiplocker.json and backpack.json files. these files are in no way 100% identifiable to the selected commander, but I guess that is already the case right now.

**Comment by jixxed** [comment]
added in 1.28
might not work completely as expected if running multiple clients simultaneously, because multiple clients write to the same files. logged an issue for that with frontier, so hopefully they will fix it in the future.
