### ISSUE TITLE
Uninstall deleted other files and folder

### ISSUE THREAD

**Issue by rmw00** [jixxed/ed-odyssey-materials-helper#24]
For installation, I selected an existing folder containing my ED reference files.  I incorrectly assumed it would create it's own subfolder.  After realizing it was now installed amongst all my other files I uninstalled.  The uninstall deleted every file in the folder as well as the folder and they did not show up in the recycle folder.  Lost forever...
Should not delete files your program did not install.

**Comment by jixxed** [comment]
Very sorry to hear this happened to you. There are applications available that can even recover files that are removed even from the recycle bin, so maybe that can help you recover some files.

Unfortunately I do not have fine-grained control over the installer behaviour. I do believe this behaviour is the default though.
see also https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html
