### ISSUE TITLE
Augmented Reality only works for "data" items in Odyssey

### ISSUE THREAD

**Issue by IAmTheDigitalCheese** [jixxed/ed-odyssey-materials-helper#244]
As the title says, I am only seeing the AR overlay when checking data points. It does not render for materials or components when on-foot or in SRV.

Because it works for data, I have to assume the OCR functionality is working, just not for materials or components.

1. I am running the game in "Borderless Window" mode.
2. My in-game language is English, my EDOMH language is English
3. I am on version 546.17 NVIDIA drivers, running a 4090
4. I am using version 14.38.33130.0 of the x86 and x64 VC++ 2015-2022 Redistributable libraries
5. Screen resolution is 3440x1440
6. Windows 10 Pro 22H2, 64-bit

If there are other steps or settings you recommend I try, I'm open to it. Thanks!

**Comment by jixxed** [comment]
There is no AR overlay for that. use the "point to" emote for assets and goods. AR is only for datapoints and bartenders to some degree
