### ISSUE TITLE
Journals location

### ISSUE THREAD

**Issue by RogueRoxy** [jixxed/ed-odyssey-materials-helper#25]
My journals save on a different drive:
F:/Saved Games/Frontier Developments/Elite Dangerous
and there are no Saved Games/Frontier Developments/Elite Dangerous folders on my C: drive.

Is there a way to have the app point to the location my journals reside?

`Roxy

**Comment by jixxed** [comment]
how did you relocate the files if I may ask?

**Comment by RogueRoxy** [comment]
I didn't relocate them. I installed the original game to the F: drive, and that's how it worked out. There's nothing I can think of other than that.

**Comment by RogueRoxy** [comment]
The Saved Games folder's dated 24 March 17. The other folder in there is Microsoft Games dated 19 Feb 16

**Comment by jixxed** [comment]
What game client are you using? Steam/epic/etc

**Comment by RogueRoxy** [comment]
Frontier. No Steam or Epic.

**Comment by Gimi1967** [comment]
A setting for journal location path would be great. It would allow the application to be run on a second computer while accessing the journals over a shared network drive.
You can move your saved games folder by going into properties and location for said folder and changing the location. That will move all the journal files. I have all my journal files on my D-drive. Hardcoding the journal path is problematic.

**Comment by jixxed** [comment]
I will add a folderpicker under settings

**Comment by RogueRoxy** [comment]
Thank you so much o7

**Comment by malkav73** [comment]
Thanks so much. I also run my 3rd party apps on a second computer accessing the journal over the network.

**Comment by mearmortal** [comment]
I would like this also please, because I also use a second machine for running apps like this, I used mapped drives.

**Comment by jixxed** [comment]
added in https://github.com/jixxed/ed-odyssey-materials-helper/releases/tag/1.26
