### ISSUE TITLE
REQUEST: Build target for Linux

### ISSUE THREAD

**Issue by GrimmerSchnitter** [jixxed/ed-odyssey-materials-helper#26]
Hi!
First of all, great work you did there.

Unfortunately, I could not get it running. As a Linux user I tend to run projects like yours from source.
It's propably based in my lack of experience using Java, but I could not get this running.

Is it possible for you to add a build target for Linux based installations or do you have any hints for compiling it under Non-Windows systems?
Any help is welcome.

**Comment by jixxed** [comment]
I am not maintaining a linux version and not looking to do so, but the application should be able to run on linux.
If you import the source into an IDE like IntelliJ you should be able to run  the application:run target. bootstrap is a seperate application for auto-updating, which you do not need if running from source.

to create your own deb installer you can customize the jpackage sections in the build.gradle files.
this article may help you configure: https://walczak.it/blog/distributing-javafx-desktop-applications-without-requiring-jvm-using-jlink-and-jpackage

**Comment by jixxed** [comment]
I have a channel in the FCOC discord, if you like to chat more directly about it.
