### ISSUE TITLE
Suggestion : overlay in VR

### ISSUE THREAD

**Issue by Ykses** [jixxed/ed-odyssey-materials-helper#263]
Hello,
Many thankx for this usefull addon ! Great work !
Can you make it to work in VR ? 
When you're at the trader, materials quantity (WL and FC) are displayed on its interface (if the game is in windowed mode), that is very usefull... but it doesn't work in VR. 
Do you think that is possible to maket the overlay also work in VR ? 
Thanks in advance for your reply :)
(sorry for my bad english ^^)

**Comment by jixxed** [comment]
Thnx.
No, VR will never be supported. It is a separate window over the game that only works in windowed and borderless modes. It would require injections into the game to even make it work and it is not something I want to spend hundreds of hours on trying to build. even fdev might take offense from it.

**Comment by Ykses** [comment]
Ah ok, I understand now !
Many thanks for your reply... and for the (sound) notification that can be heard when you pick up materials you need :) (very usefull in VR).
Keep up the good work.
