### ISSUE TITLE
Won't Launch After Update

### ISSUE THREAD

**Issue by enrogae** [jixxed/ed-odyssey-materials-helper#266]
Got the notification about a new version and auto updater.  Downloaded the auto-updater, installed, launcher ran and pacman said it was updating, then launching app... then it closes without doing anything.  Now it just closes without doing anything every time I try to launch it.

**Comment by enrogae** [comment]
I did check the task manager. There was no process to end. I even uninstalled the app and reinstalled it. Still wouldn't launch. Just says launching then does nothing. I didn't have the auto launcher before so I didn't download it again.

**Comment by jixxed** [comment]
you can check the log for errors %localappdata%\Elite Dangerous Odyssey Materials Helper Launcher\log
if the issue still persists even after a reboot, you can send the log and latest journal file (directly on discord if you prefer)
then I can try to reproduce your issue.

**Comment by enrogae** [comment]
Log doesn't appear to show any errors, app still isn't launching.  This is after a reboot.  Only way I seem to be able to get it to work is to uninstall the launcher and install using the portable version.
[edomh.log](https://github.com/jixxed/ed-odyssey-materials-helper/files/14424295/edomh.log)

**Comment by jixxed** [comment]
well the auto updater actually downloads and launches the portable version for you. There is an exotic issue related to non standard characters in Windows usernames, for example if you have Æ in your windows username. then it helps installing the auto updater to the same location as you would for the portable version, since that seems to work for you. it's important there are no special characters in the path to the executable.

the log indicates the app isn't loading at all indeed, so it isn't even getting to the processing of the journal.

**Comment by enrogae** [comment]
There are no special characters in my Windows username.

**Comment by jixxed** [comment]
it does/should
![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/14129491/29d46e30-98a6-4caf-af51-31f0cc2eda72)

**Comment by jixxed** [comment]
I gave the msi a try here. seems to have an issue. you can install the version 2.44 of the msi. that one seems to work

**Comment by jixxed** [comment]
a new minor(21.0.2) version of java was released Jan. 22nd which was automatically used to build 2.46 and 2.47. 2.45 uses 21.0.1 and does not appear to have this issue. Unfortunately I can't specify a specific minor version for the build. Will try some other distributions to see if I can work around the issue for now for 2.48.

**Comment by jixxed** [comment]
Currently building and releasing 2.48 using 21.0.1. you can give this one a try if like.

**Comment by jixxed** [comment]
confirmed 2.48 works for me

**Comment by enrogae** [comment]
Will do! I'm back at work this morning but will definitely give it a whirl
later today or this evening!

**Comment by T-C-24** [comment]
Hi, I was trying to install the windows version last night and was getting the same issue as enrogae, so I also could only get it working with the portable version. I have just installed your new version 2.48 and I've got it running now, thank you

**Comment by jixxed** [comment]
Thanks for the update. I've added it to the release notes for others to find.

**Comment by enrogae** [comment]
Just downloaded 2.4.8 and it works flawlessly, thank you!

**Comment by 4lexcha** [comment]
Have the same problem. Uninstalled the autoupdate and installed it back. Worked for the first time, the next day - again, app is not starting after launcher.

[launcher.3.log](https://github.com/user-attachments/files/21722384/launcher.3.log)
[launcher.2.log](https://github.com/user-attachments/files/21722385/launcher.2.log)

[edomh.log](https://github.com/user-attachments/files/21722406/edomh.log)

The process is there but no UI on the screen:
<img width="865" height="452" alt="Image" src="https://github.com/user-attachments/assets/fa236e46-2f4d-4c47-a27b-533c14628c91" />
