### ISSUE TITLE
Shortest travel path planning doesn't consider engineer at docked base 

### ISSUE THREAD

**Issue by Charybdis** [jixxed/ed-odyssey-materials-helper#267]
I've docked at Farseer Inc at Deciat to apply experimental effects to several thrusters. While Farseer doesn't have G5 engineering she can still apply experimentals.

The route planning is suggesting Elvira Martuuk as the engineer that should be visited. I'd expect Farseer to be offered as the 0Ly distance option.

Thanks for taking a look!

![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/23155785/23ee6c72-ec2c-4711-b7ef-6d371e90a7d5)

**Comment by Charybdis** [comment]
I've had a chance to play with this a bit more. The initial calculation when you are docked at the engineer works just fine: you get a 0Ly recommendation.

The problem seems to occur while you are travelling between engineers, and updating based on actually arriving at one of the engineers on the route.

To be clear: all experimental effects was added before visiting Farseer, and other blueprints were applied to the ship at Farseer (FSD) before checking ED:OMH again. ED:OMH was not updated, I was only removing completed engineering at Farseer as I progressed.

Hope this helps with any repro.

**Comment by jixxed** [comment]
probably due to the fact you don't have any blueprints to craft at Farseer. blueprints have a higher priority to be crafted to prevent the scenario that you are sent somewhere to apply an experimental effect before applying a blueprint, which might not be possible. It is not easy to incorporate this scenario and I will probably rework this in the future so effects and blueprints are linked.

**Comment by Charybdis** [comment]
No blueprints left to apply is exactly the case - nice analysis. In practice you can apply an experimental on a single tier 1 blueprint applied to the module, though I suppose an engineer could be eliminated from pathing if they don't offer the blueprint level that you are also going to engineer.

With remote engineering you mostly only need to visit the Engineer to get the experimental (I've set up pinned blueprints for this reason). This is the use case that found this behaviour.

Thanks for the insight into the priorities - it does make sense - and this is certainly an edge case. Not so much of a problem as I'm going to the engineers with a good idea of what does need crafting anyway.

Cheers for taking it on board.

**Comment by jixxed** [comment]
was able to optimize it :) will be part of the next release

![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/14129491/207eb5d9-722b-417f-a2f4-e48ca4bc6c4b)

**Comment by Charybdis** [comment]
Many thanks for this. A most wonderful utility for Elite Dangerous just got a bit better.
