### ISSUE TITLE
Unable to locate Odyssey Journal

### ISSUE THREAD

**Issue by jasehuss** [jixxed/ed-odyssey-materials-helper#27]
![image](https://user-images.githubusercontent.com/78591880/126166658-343b85fe-c98e-44d0-a8c0-bb7b1934c242.png)
[New Compressed (zipped) Folder.zip](https://github.com/jixxed/ed-odyssey-materials-helper/files/6841244/New.Compressed.zipped.Folder.zip)

Journal, shiplocker and backpack files provided in zip file

Thanks in advance

**Comment by jixxed** [comment]
I can read the files without issue. Is there perhaps an antivirus on your system blocking access to these files?

**Comment by jasehuss** [comment]
I'll take a look, thanks for the quick response. I'll let you know of the outcome

**Comment by jasehuss** [comment]
okay, think I have found the issue. my users\saved games folder is on drive D: can I get your program to look on there?

**Comment by jixxed** [comment]
added in https://github.com/jixxed/ed-odyssey-materials-helper/releases/tag/1.26
