### ISSUE TITLE
Error on loading v 1.26

### ISSUE THREAD

**Issue by jasehuss** [jixxed/ed-odyssey-materials-helper#28]
Thanks for the prompt response on the previous issue and my apologies, it seems like I'm just bringing problems.
I uninstalled the previous version and installed 1.26 and now get this on startup.
![image](https://user-images.githubusercontent.com/78591880/126179864-99a1d771-2cbc-4585-a879-ccab98801b22.png)

**Comment by Gimi1967** [comment]
Getting the same error. Using the portable version.

**Comment by RogueRoxy** [comment]
Ditto

**Comment by mearmortal** [comment]
Same error here too with the portable version..

**Comment by jixxed** [comment]
made a fix in https://github.com/jixxed/ed-odyssey-materials-helper/releases/tag/1.27 that should at least fix the exception.

**Comment by jixxed** [comment]
I expect this was caused by the folder for the journals not existing in the expected location. The application should now start, allowing you to change the journal location under Settings.
