### ISSUE TITLE
Translation errors of the tabs in German & shipbuilding formatting errors

### ISSUE THREAD

**Issue by PeterMayerHamburg** [jixxed/ed-odyssey-materials-helper#280]
1. Translation error of the tabs in German

OnFoot (False) On Foot (Correct)
Ships (False) Shipbuilding (True)

2. Formatting the right edge of the page in shipbuilding, the side text goes beyond the edge of the page -> not readable

I would estimate that there are about 6 characters, maybe reformat so that they come further to the left

Even if I move the window to the left to open the window further to the right, I don't get all the missing characters displayed, maybe reduce the scaling

**Comment by jixxed** [comment]
1. No new localizations have been added with the new feature. Some have changed. It is up to the community to add the correct translations
2. a screenshot can help identify the issue. The shipbuilder currently works with a collapsed menu @ 1920x1080, 100% scaling and default text size.
