### ISSUE TITLE
[BUG] Ship Editor content overflow

### ISSUE THREAD

**Issue by Mef45** [jixxed/ed-odyssey-materials-helper#281]
Following the recent update introducing the Ship Editor, there's an issue where the content displayed within it overflows the available space, rendering it impossible to view it entirely.

Env: win 11, resolution 2560x1600, scale 150%

The layout scheme of hardpoints on the ship does not fit within the screen. Additionally, the Armour is cropped by 1/3 and cannot be scrolled through.

<img width="1280" alt="image" src="https://github.com/jixxed/ed-odyssey-materials-helper/assets/26562037/e59cc97d-4348-4cd9-bea3-81639039bb03">

---

The list of available ship mounting points does not fit horizontally even though I've scrolled through it as much as possible (it's simply impossible to scroll further than what is shown on the screenshot)

<img width="1280" alt="image" src="https://github.com/jixxed/ed-odyssey-materials-helper/assets/26562037/2eb6e633-a599-443f-a240-c6f0cdf84c52">

**Comment by jixxed** [comment]
you can collapse the menu ( < button above the tabs)
the UI is currently not designed to be responsive and is targeted for 1920x1080@100% with default text size
