### ISSUE TITLE
error

### ISSUE THREAD

**Issue by slavyanin13** [jixxed/ed-odyssey-materials-helper#282]
[hs_err_pid3768.log](https://github.com/jixxed/ed-odyssey-materials-helper/files/14814131/hs_err_pid3768.log)
Error when updating the program and the program no longer starts

[Elite.Dangerous.Odyssey.Materials.Helper.Auto.Updater-2.51.msi]

**Comment by jixxed** [comment]
not sure what causes this issue for you. It appears to be something in java itself.
There is an upgrade planned when the java 22.0,1 is released. That should have a bug fixed that prevented other updates.
This is scheduled for April 16th. Not sure if that will fix your issue though.

**Comment by jixxed** [comment]
update has been released https://github.com/jixxed/ed-odyssey-materials-helper/releases/tag/2.58

You can test and see if this works for you.
Will close this issue if there is no further response in the next week
