### ISSUE TITLE
Feature Request: Asset type in HUD?

### ISSUE THREAD

**Issue by ZanyScum** [jixxed/ed-odyssey-materials-helper#284]
You already show for data if it is useful, this is incredible helpful!

Could you use the same logic to show in the HUD if the seen asset is something you could use to trade with the bartender for something you need, or if you directly need it?

There are three types of assets, so it is kind of bad to bring back every asset.

**Comment by jixxed** [comment]
there is a point to emote available for assets and goods. you can trade all assets(open lockers) and sell goods(closed lockers)
once you hit 1000 assets it is best to trade them into the most expensive items in their categories. that way your storage holds the most value and you can trade them back when you need it.

**Comment by ZanyScum** [comment]
You are kind of right. But.. :-)
When you are at 9xx/1000 and have "Extra Backpack Capacity" and go for 4 missions at once, then you will end up having to destroy some in front of your ship/shuttle.
So, why bother collecting stuff you don't need?
I have currently - for example - everything but "Data", "Weapon Component" and some things I don't know what kind they are.
So currently I only want to collect assets of the subtype "tech". But perhaps I am the lone one here. In that case it makes no sense to develop just for me. 
If it were a common problem, you would probably have read about it before.

**Comment by jixxed** [comment]
could add a (sub)type to the notification popup title

**Comment by ZanyScum** [comment]
The HUD thingy is complicated?
IF you want to invest time and IF the work is in the same category, then the HUD indication would be much better, because you see the HUD before you loot but you see the notification after you loot.

But please keep in mind that not many people buy Elite and will use this. I guess this because of the non existing new comers in the Steam forum.

So, perhaps your time would be wasted. :-(

**Comment by ZanyScum** [comment]
> the point to emote provides a notification before picking it up. An overlay like for data is not possible unless you game on a supercomputer.

Ahh. I suppose you are talking about this:
![2024-04-04-Materials-Helper-Settings-Point-to](https://github.com/jixxed/ed-odyssey-materials-helper/assets/46635062/9f07d74c-fb00-4999-839b-22df31b32063)

I was hoping it would do what you just mentioned but it never worked for me. So I guessed it did something different.

The idea is, I point at an asset or good and a sound will play, depending on these settings?
What could be the reason it is not working for me?
Do I need perhaps another tool or something?
