### ISSUE TITLE
FC endpoint warning on startup

### ISSUE THREAD

**Issue by frfrh** [jixxed/ed-odyssey-materials-helper#288]
Whenever I start EDOMH I get a warning that the FC endpoint returns empty response, asking me if I own a FC. Which I actually don't. But I also can not find a setting to turn off this warning. Am I missing something?

![grafik](https://github.com/jixxed/ed-odyssey-materials-helper/assets/93924020/812c0d71-8898-4c1e-b457-c8fc339dbaa2)

**Comment by jixxed** [comment]
Yes the api is only used for fleetcarrier data so the warning lets you know it has disabled fetching data. There was the intention to use the api for more but fdev never implemented additional data for loadouts. You can just disable the api as long as you don’t own a fleetcarrier or ignore the message.

**Comment by frfrh** [comment]
You mean the "Frontier API Integration" setting is only needed if you have a fleet carrier? That wasn't clear to me, I thought this will pull other data as well. Maybe add a short hint to the text of the setting to make it more clear. Something like
```
Only needed of you own a Fleet Carrier.
```

**Comment by jixxed** [comment]
warning is now removed
