### ISSUE TITLE
Auto Update Prompt

### ISSUE THREAD

**Issue by lanzz** [jixxed/ed-odyssey-materials-helper#294]
Every time I start the application, it pops up a notification that there is an update available, and asks if I knew that there is an auto updater. But thing is, I _did_ install the auto updater version (`Elite.Dangerous.Odyssey.Materials.Helper.Auto.Updater-2.56.msi`), but for some reason it doesn't seem to, well, auto update. I don't see anything related to auto updates in the settings, and I have no idea how to diagnose why it isn't updating.

**Comment by jixxed** [comment]
You have to launch the app with the launcher, which should be in the start menu. this is a little pacman program that will update for you if there is an update available and launch the application
