### ISSUE TITLE
incorrect material trader

### ISSUE THREAD

**Issue by Minecrafter8001** [jixxed/ed-odyssey-materials-helper#297]
im at zerreiss station in the Pru Euq WO-D b53-8 system and the material trader here is an encodeded one but EDOMH shows the nearest encoded trader as over 1,200LY away and this trader as a Raw materials traider
![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/133237713/90f22c95-9313-411e-bf34-64400b3160a6)
![20240422164923_1](https://github.com/jixxed/ed-odyssey-materials-helper/assets/133237713/f30e64f4-d01a-4382-b6b7-b480a0f7b92d)
not sure where EDOMH gets its material trader info from but this is clearly incorrect

**Comment by Minecrafter8001** [comment]
https://www.edsm.net/en_GB/system/stations/id/22268120/name/Pru+Euq+WO-D+b53-8/details/idS/189531/nameS/Zerreiss+Station
https://inara.cz/elite/station/460905/
EDSM and INARA both show this system as an encoded materials trader not a Raw one

**Comment by jixxed** [comment]
The data was originally scraped from Inara. The specific type is however not supplied by journals but provided by users. The types are therefore subject to change.
Will give this one an update, thnx for the report
