### ISSUE TITLE
FEATURE REQUEST: filters and helps

### ISSUE THREAD

**Issue by towingie** [jixxed/ed-odyssey-materials-helper#3]
awesome tool! need some improvements :-)

- make mouseover help where such type of material can be obtained with drop rate or something like that
- show separately/under filter completely useless materials which can be sold ASAP

**Comment by OzDruiD** [comment]
Additonal filter that would be a fantastic help....
Tickbox like the ignore irrelevant optopms. but the reverse of that - Only SHOW irrelevant and\OR Only Show irellevant (Data,Goods,Assets)

Basically for the simple reason to  easily view and then vendor all that rubbish 
- picking through, with the side by side columns and legend isnt easy with 1000 items in each catagory.

In any case-  saved my sanity so thanks HEAPS for this amazing piece of work in repsonse to the dire need in the community.

**Comment by OzDruiD** [comment]
Just realised Towingie updated this filter request - so basically yes - huge support for the "Show irrelevant only" type filter.

**Comment by jixxed** [comment]
Personally I am a billionaire in-game so I had not even considered this. I only wanted to pick up relevant items. Getting this type of feedback is important, because everyone plays the game differently.
I will definitely look at improving sorting and filtering on the short term.

**Comment by OzDruiD** [comment]
Thanks - also a multi billionaire - in the carrrier bank - alone has 120 years of carrier fees :P  and personal as well - but the beneifit of filter irrelevant .. is clearing out your storage limit was well, less the $$ credits.

Thanks heaps for reading\responding.

**Comment by jixxed** [comment]
feature placed on the backlog: https://github.com/jixxed/ed-odyssey-materials-helper/wiki/Planned-Features
will close this issue
