### ISSUE TITLE
Jar

### ISSUE THREAD

**Issue by alexzk1** [jixxed/ed-odyssey-materials-helper#30]
Can you just make JAR file?
I play from Linux and all that exes ... 

Gona compile meself, but that would be easier just download jar & run it.

**Comment by alexzk1** [comment]
...i see already it is windows only. You will need those code pieces (I added in class public class PreferencesService)

```
private final static String OS = System.getProperty("os.name").toLowerCase();

private static String PREFERENCES_FILE;
    {
        if (isWindows())
            PREFERENCES_FILE = System.getenv("PROGRAMDATA") + "\\odyssey-materials-helper\\pref.properties";
        else
            PREFERENCES_FILE = System.getProperty("user.home") + "/.config/odyssey-materials-helper/pref.properties";
    }

 public static boolean isWindows() {
        return OS.contains("win");
    }

```

Also it doesn't work for me with "Observable" yet, maybe I downloaded wrong library...

**Comment by jixxed** [comment]
I do not support Linux as I haven't gotten an environment for it set up. 
If you use IntelliJ, and you import the project, gradle should take care of all dependencies.
You can contact me on discord if you like work on linux support for the application. If you get it to work properly, I can add deb/rpm packages to the releases.

**Comment by alexzk1** [comment]
Just build proper JAR, which can be launched as 

java -jar project.jar

No need to pack things like bootstrap, updater, whatever. System has installed java.

**Comment by alexzk1** [comment]
JAR should have copies of all libraries used inside it to avoid downloading etc. So that will be single big (zip) file containing compiled *.class files + resources. 
I think you may need to deal with resource loading from inside jar too.

**Comment by jixxed** [comment]
cannot support this specific usecase, but feel free to pull and build it yourself. If you like to contribute code changes, you can fork and create a PR.
