### ISSUE TITLE
Not a bug just a request

### ISSUE THREAD

**Issue by FryaDuck** [jixxed/ed-odyssey-materials-helper#31]
Excellent work on the mod. A real benefit to the community.

In the Engineers tab if you could match the Engineer with those in the Engineer Unlocks (change the name to green text), Modules (any unlocked or not) change the text to green when there are sufficient materials for that module. 

Thanks in advance

**Comment by batkung** [comment]
mouseover/clicking on the engineers picture ( or name in the modules selections) should display the unlock requirements for that engineer

**Comment by jixxed** [comment]
will add some of this to the next release. for materials quantity checks I want to revamp the wishlist section first.

**Comment by jixxed** [comment]
blueprints for suits and weapons will be highlighted like completed engineers if enough materials are present.
this will be the final update for this feature request. will be released with 1.39
