### ISSUE TITLE
The shipbuilder shows N/A for the full thrust and FSD heat generation values for the Current ship (read only)

### ISSUE THREAD

**Issue by paladinkolovrat** [jixxed/ed-odyssey-materials-helper#321]
The shipbuilder shows N/A for the full thrust and FSD heat generation values for the Current ship (read only).
Have no issues with custom ships.

**Comment by jixxed** [comment]
can you provide the loadout event of the ship that has the issue? otherwise I have very little to go on.

**Comment by paladinkolovrat** [comment]
> can you provide the loadout event of the ship that has the issue? otherwise I have very little to go on.

It seems, the last update fixed that.
