### ISSUE TITLE
Proto Radiolic Alloys location is wrong

### ISSUE THREAD

**Issue by vanderaj** [jixxed/ed-odyssey-materials-helper#324]
The correct combination of states is: Alliance, High Tech, Boom, High Population. This may also apply to independent systems, I will check over the weekend.

**Comment by vanderaj** [comment]
Independent Boom High Tech High Pop produced Proto Heat Radiators.

**Comment by vanderaj** [comment]
After dropping into a lot of the independent high tech boom high pop USS, proto radiolic alloys can occur, but at around a 4:1 ratio between proto heat radiators : proto radiolic alloys.

**Comment by jixxed** [comment]
what change exactly are you suggesting here?
This already seems to cover it pretty well
![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/14129491/9ae7123d-d890-4730-ab1c-9108915a98de)
