### ISSUE TITLE
wrong info

### ISSUE THREAD

**Issue by vnrider1500** [jixxed/ed-odyssey-materials-helper#325]
broo tarquin app upgrading multi cannons now

**Comment by vnrider1500** [comment]
[cid:e9d52a16-86c8-4587-9f17-3cbe5b25ab72]


________________________________

**Comment by vnrider1500** [comment]
![Screenshot (4)](https://github.com/jixxed/ed-odyssey-materials-helper/assets/170365583/a20ff018-974d-4f3c-b094-e51454e64eda)

**Comment by vnrider1500** [comment]
as you can  see broo has multi cannons

**Comment by jixxed** [comment]
ah and you were trying to say that in game he doesn't. clear now. looks like the G5 Efficient Weapon blueprint had the error. will be fixed for next release. thnx for the report :)

**Comment by jixxed** [comment]
fixed in 2.70
