### ISSUE TITLE
The routing calculator does not take into account experimental effects.

### ISSUE THREAD

**Issue by Cashiot** [jixxed/ed-odyssey-materials-helper#329]
As I said in the title, since a few updates ago, if you only mark the experimental effects, it does not take into account most of them to calculate the optimal route.

![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/86895431/632e5de6-a0df-44a0-844e-a8e3dc8abbdd)

**Comment by jixxed** [comment]
can you add a copy of the wishlist(edomh:// link)?

**Comment by Cashiot** [comment]
Of course, here you have it, but it happens with all the lists I have, even with those of friends. Could it have to do with the localization? We play in Spanish, although the language of the program does absolutely nothing.

> edomh://horizonswishlist/?eNrdVdtu4jAQ_ZWVn0EiEArkzeuYxCJxItspqqrKSsFVLYWAktC9VPx7zVLUajebRe22kXiJRp7xzDlnxplHoB5UXgEHfNPlfabLCnTAgypKvc6BY3Vejp1HsN3qpYm07EWajifDrnXXW3TtO5V2b1U66I4X9mihJhOrn6YmS56ulIkWukrzLzOdZaowp7pSqxI414-g-rHZ-1fr5TZTxvOcvWfMQi30RtFfCa7B_brQP9d5aRwIJlwQJDmhMxnAhCIfM3DTAbfZVm0KnVfikBWGYSQRjCEi4gq88ntFulRsnWXlnpHHoIulBZz-btf5KySrCRJkYZTUYvAxvLySbnIagM6z3QfO4GgPgGMfbRs4w6M9NK3pvUasvm9UoVemk2n2grv_NtwuxrGMAygI9UCDLIOm9HE0x2yfhYq6GkE0lzgknJOI8pbksd-BX5i5C2EgecwwdJtUGjZVET4zA40Zr6uBAgypdBm5xFIkdN-NdoS6eDOF02UaNdWYMhhiyX0yFQc96moRikwRjl055a5kkHr4w_X6ncW4iUVApoZEEscRq38TxPPFHO-_nw588u-34BIuGPmaiKj2r4F8yDwsMfUhRdhtaVSt3ruJmA6ZIBRRNyGCN82s1bgYOKY8qn8WQUS9w4RKjiClZod9dsOtxuXgJ0EgGSZ0GjGEQ0yFNKt0Bj3cvOjknxfbGoTB_-N36kK07DPXdNiCphdnrumoBU3HZ67p5KM0vdntngAHZQ5S


And here is another wishlist:

![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/86895431/358ad0f0-4df8-4d43-a484-6895b11b5f7f)

> edomh://horizonswishlist/?eNrdl1tvokAUgP9KM8-aCCJV3qYwwqQwkJmhpmmaiZdJJItiALuXxv_eYV23Zkvopq4l64s5cQ7nzPnODZ6BfJLrEljga1Is06QoQQc8ybxIsjWwtM7r39Yz2G6ThdLsmYYptfm8aw57Ztcwr0fd2Wg07OqmnJkjdTTQDWVlPV1Jpe1k6WaZrK8W8irYyqLMp4U6TEq5KoD18AzK75tKbZUttqlUJwcnSszlPNlI8tPOA1hmefIjW1dP3yAYCB8yRMFjB8zSrdzkybrke1N-SFxBIXGRmCAYhQQc6bj5dCFplqZFFZFLoYOEBiy980vWgWUc5D6wzINsAGt4kAeKTG-36_y-vPy2kXmyUiCn6WsI2sdD4B6iAfTFHSIcHDn6k5L-_1Pqn5-S0eQC0iCMa817CN7dCyfm9y2hGXzs3g5CkYh8yDFxm7CYTeajcIJoZUWhra2eiUABZgyHhLWE5_qE-x9Kh0UUQaeJ0rDJC_dozDiirDYPmHJVPxTfIcFjUmWjHVCjj4dAobuPgDUx0hqn9ZjCAAnm4THf26rzhImtMsGQI8bM2c-ltsa2dnIwAWRMBJBAVw2uJm6N89vHY-UpjqKQ1vcgdj0-QdXv2VG9uXn__eZzMOMU38Q8rB1TtgepWj6IeJDYyGkr28bJgagUKSU7JE6MeXOfNE50hggL6_vwaFkzGxKiyurTM964LrzY9wVFmIxDaqNALWQRQftWNUDzZhVvH2yrEK7_XXx_u4G14YUzHX0-U7132Ux1rQWm-oUz7bfA1LhwpoPzMy3lfDnLsy8yP_L7zp5Sr2UiCJ3YR7WblmGKYyYUUS4YJrfq6zMmtle9xz3udi_D7Uir

**Comment by jixxed** [comment]
No, there is an optimization so the blueprint and effect get paired, so you don't get sent somewhere for the effect before the blueprint(can happen if the engineer doesn't go up to the desired grade)
seems that hiding does not take this into consideration, deleting the blueprint does.

**Comment by jixxed** [comment]
![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/14129491/66860a0f-0fa7-4d78-a696-5cedfad75a26)
fixed for next release. thnx for the report!

**Comment by jixxed** [comment]
fixed in 2.71
