### ISSUE TITLE
Left Window pane

### ISSUE THREAD

**Issue by valavirgilin** [jixxed/ed-odyssey-materials-helper#33]
On the left window pane, where you can open and close all the stuff you need, my Weapon Module dropdown list is empty. I can't see what you need for Scope or magazine size etc. However adding it to wishlist is no problem.
![window pane](https://user-images.githubusercontent.com/87898425/126890589-4ab0d328-fed4-4f01-bcce-4aaa468ac570.jpg)

**Comment by jixxed** [comment]
will fix it in the next version with a new style supporting smaller screen sizes

**Comment by jixxed** [comment]
should be fixed in 1.32!

**Comment by valavirgilin** [comment]
Great work, thank you very much.

On 25-7-2021 23:05:05, jixxed ***@***.***> wrote:
should be fixed in 1.32!
