### ISSUE TITLE
How to make overlay work on linux?

### ISSUE THREAD

**Issue by InnerBushman** [jixxed/ed-odyssey-materials-helper#347]
I have the app downloaded and it can read the journal just fine. I can point at things and I get the notifications in the bottom right corner.
One thing I don't know how to make work is the overlay when I download the data.
Please help? :)

**Comment by jixxed** [comment]
Enable it on the Settings tab under Augmented Reality

**Comment by jixxed** [comment]
nvm, just read linux, this is a windows only feature

**Comment by InnerBushman** [comment]
Is there a reason it's Windows-only feature?

**Comment by alexzk1** [comment]
> Is there a reason it's Windows-only feature?

Yes. For Linux it needs 2 different versions too, for xserver and for wayland. Also on linux "menu shadows / transparency" are optional, and overlays need it to work. Other words it is not trivial task.
I made overlay for EDMC + xserver (no wayland): 
https://github.com/alexzk1/edmcoverlay_for_linux

If authors want they can reuse binary which draws overlay. I kept in mind it can be used for the other purposes. However, I have no idea if it will be any conflicts if 2 such binary will run for EDMC and this one.

**Comment by jixxed** [comment]
A lot of work for just a handful of people playing on linux and using the app. Linux compatibility is only there because it is easy to add for the larger part of the application. This is the only thing that doesn't. Perhaps you can try to make it work with proton.
