### ISSUE TITLE
Request: Ability to print wishlist 

### ISSUE THREAD

**Issue by Jibsman** [jixxed/ed-odyssey-materials-helper#35]
EDEngineer does a screenshot. I'd prefer a .txt file of the required mats to print out and keep close so I remember what I need.

Excellent work & very useful. I'll buy you a beer on payday.

**Comment by jixxed** [comment]
implemented for the next release. thanks for the donation! :D

**Comment by Jibsman** [comment]
Thank you for implementing this! Beautiful! Now I can easily refer to what I need and not leave the game!!!
I'll buy you a beer sometime this next week. Cheers!
