### ISSUE TITLE
installed sizes...

### ISSUE THREAD

**Issue by alexzk1** [jixxed/ed-odyssey-materials-helper#355]
It's a sort of complain. In 1997 I had "MS Encarta" CD disk, it was 600 Mb of the whole World map, with articles about most cities, pictures and short movies.
Now I tried to install this program, it got 300 Mb of the dependencies + own size (full java is in). Really?

**Comment by jixxed** [comment]
And MS Encarta didn't even communicate with the web and do image recognition and OCR? What a long way we've come....
The application is modularized, so not even the entire JDK is in there.
