### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by alexzk1** [jixxed/ed-odyssey-materials-helper#36]
I'm a bit tired to merge changes after each pull .. so would be cool if you update those 2 files. Changes needed to run on Linux.
Compilation to jar is just question to proper configure idea to build artifact.
[linux_fix.java.tar.gz](https://github.com/jixxed/ed-odyssey-materials-helper/files/6907766/linux_fix.java.tar.gz)

**Comment by jixxed** [comment]
please create a PR so it can be reviewed.

**Comment by alexzk1** [comment]
Nah, don't want to bother...that needs to make clone on site, then local clone, then edit local clone, then push it...too many things to do for 20 lines about.
