### ISSUE TITLE
[Bug] Ship editor: Caustic and Explosive resistance are swapped

### ISSUE THREAD

**Issue by IamKayrox** [jixxed/ed-odyssey-materials-helper#360]
In the ship editor, Caustic resistance has the Explosive resistance values and Explosive resistance values have the Caustic Resistance values.

**Comment by IamKayrox** [comment]
As a reference here are the values I'm getting in EDSY:
![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/11013910/d45cea66-039d-4b86-bb80-567e72ce3750)
Here are the values I'm getting in EDOMH with the same build:
![image](https://github.com/jixxed/ed-odyssey-materials-helper/assets/11013910/5f8e8972-239d-40ce-aa07-e0b01f5aa11e)

**Comment by jixxed** [comment]
thnx, seems the labels got swapped. fixed in next release
