### ISSUE TITLE
Cat Media

### ISSUE THREAD

**Issue by Jibsman** [jixxed/ed-odyssey-materials-helper#37]
Was selling to the Bartender. I had Cat Media, and I couldn't find it on your Irrelevant list.
There was at least one other I couldn't find on your list but did find it on Inara as not having any engineering value.
You might want to have someone double check that list.
Cheers!

**Comment by jixxed** [comment]
Cat Media is an engineer unlocking material(Wellington Beck) and is therefore not completely irrelevant. also after the unlock you might want to save it to share it later on.
I could add a toggle to the settings to show/hide it depending on your playstyle.

**Comment by Jibsman** [comment]
No, you are correct. I will close this issue. Apologies.
