### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by Dbariri** [jixxed/ed-odyssey-materials-helper#370]
Hi.
I am getting a virus warning since the last update (2.87).

`cached<hti>!276b6287`

![image](https://github.com/user-attachments/assets/258c818d-14fd-47b7-a6bd-914476d35ecd)

Thanks for your help.

**Comment by jixxed** [comment]
https://www.virustotal.com/gui/url/74abf8dba33406cc134a1474e2d188a413083f7052441dedfa31262fdc5be77a?nocache=1

**Comment by jixxed** [comment]
every version is always submitted to virustotal in an attempt to reduce false positives, but it is an issue with some AV vendors, mostly when using AI.
