### ISSUE TITLE
It does not start

### ISSUE THREAD

**Issue by succub676** [jixxed/ed-odyssey-materials-helper#377]
Good afternoon. I created a wish list, and during the editing process, the display of the required materials disappeared. When restarting, it gives an error. I ask for your help please/
![1](https://github.com/user-attachments/assets/e9d5eeec-9689-45a4-8326-bd9f2eda0f6e)

**Comment by jixxed** [comment]
can you share your horizons_wishlist.json file from %localappdata%\odyssey-materials-helper

**Comment by jixxed** [comment]
fixed in 2.91. caused by setting all grades of a blueprint to 0%

**Comment by succub676** [comment]
> can you share your horizons_wishlist.json file from %localappdata%\odyssey-materials-helper

I deleted folders containing wish lists and it didn't help

**Comment by succub676** [comment]
> fixed in 2.91. caused by setting all grades of a blueprint to 0%

the whole problem started with the "%" setting

**Comment by succub676** [comment]
only one thing helped, the complete removal of all files and traces, along with "C:\Users\user\AppData\Local\odyssey-materials-helper "
