### ISSUE TITLE
Request: Can you add a sort option for illegal items?

### ISSUE THREAD

**Issue by Jibsman** [jixxed/ed-odyssey-materials-helper#38]
In the section where I can display All items, Irrelevant items, etc. Could you add a "Illegal Items" so I can see what I need to sell to Anarchy Bartenders?

Thanks! I still owe you a beer for the list printout!

**Comment by jixxed** [comment]
I have to see if I can find out which items are considered Illegal exactly. Haven't kept track of that myself.

**Comment by Jibsman** [comment]
If I find the list I'll share it here.

**Comment by Jibsman** [comment]
Illegal Drugs:
Push, Lazarus, Hush, Genetic Repair Meds

Bioweapons/Sabot material:
Synthetic Pathogen, Pyrolytic Catalyst, Inorganic Contaminant, Mutagenic Catalyst

Data:
Biological Weapon Data, Kompromat, Spyware, Virus

There may be more... still searching!

**Comment by jixxed** [comment]
I just got this list by visiting a station and checking the storage from the ship:
these are marked also in anarchy system as prohibited(need to test if it depends on station)
pyrolytic catalyst
mutagenic catalist
biochemical agent
synthetic pathogen
inorganic contaminant

virus
spyware

above and below are prohibited in non-anarchy station:
hush
lazarus
push

biological weapon data
chemical weapon data
enhanced interrogation recordings
espionage material
kompromat
slush fund logs
smear campaign plans

PS: Genetic Repair Meds do not show as prohibited

**Comment by Jibsman** [comment]
Wow great list! Thanks for doing that! If you have time to add it that's great!
Cheers!

**Comment by Jibsman** [comment]
Where do I go to buy you a beer? Can't find it...

**Comment by jixxed** [comment]
There should be a donate button in the About section in the menu on the left.

**Comment by Jibsman** [comment]
10 EUR on it's way. Thanks for adding the print txt button. 
I take the text, turn it into a spreadsheet, remove the "zero needed" items and sort alphabetically. That really helps me figure out what missions I need to do to get the right mats!


Thanks again,
Happy Daze / John

On August 4, 2021 at 5:58 AM, jixxed ***@***.***> wrote:






There should be a donate button in the About section in the menu on the left.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jixxed** [comment]
Thanks for your donation! I will look into adding xls support soon. that should save you a step.

**Comment by jixxed** [comment]
implemented 1.36
