### ISSUE TITLE
Modified Shard Cannon description is wrong.

### ISSUE THREAD

**Issue by mlynn65** [jixxed/ed-odyssey-materials-helper#389]
Under the description for Techbroker Guardian Weapons > Modified Shard Cannons (medium and small), the description is for Modified Plasma Chargers with overcharged and focused blueprints. Those blueprints can't be added to Shard Cannons.

![Clipboard Image](https://github.com/user-attachments/assets/facde9ff-dcdd-4903-b33a-0111e548622d)

**Comment by jixxed** [comment]
thnx for the report! fixed in 2.95
