### ISSUE TITLE
Update after using material

### ISSUE THREAD

**Issue by Jibsman** [jixxed/ed-odyssey-materials-helper#39]
I noticed I had a green weapon grade blueprint. Yay I can upgrade something!

I upgraded my weapon but the material count didn't drop. I closed the app and opened it again and it still had the same inaccurate information.
I figured it would reread the json file after closing and reopening.
Is there an "Update" button I'm missing to reread the json file?

If not you might want to check this.
Let me know if I need to do something to update the mat count.
Cheers!

**Comment by jixxed** [comment]
It might indeed not be accurate in all situations. The backpack for example, does not update after you enter your ship. If you can share your journal, I can see if there is something that can be done. There is probably no ShipLocker event after the purchase, but perhaps an event indicating the purchase coincides with an update to the shiplocker file.

**Comment by Jibsman** [comment]
I have EDDiscovery which tells me when a Ship Locker event happens. I'll check after the next purchase. Meanwhile where do I upload my journal (and I have to remember where it is...)

**Comment by jixxed** [comment]
you can upload them here, or send them to me over discord. You should be able to find me in any of the popular ED servers. I also have a dedicated channel in the FCOC discord.

**Comment by Jibsman** [comment]
[Elite Dangerous.zip](https://github.com/jixxed/ed-odyssey-materials-helper/files/6934634/Elite.Dangerous.zip)

Wasn't ssure what you needed, so I zipped up a few logs and jsons. If you need something different or more just let me know.

**Comment by jixxed** [comment]
all I need is the Journal*.log file from the day you bought the upgrade. If you capture the files immediately after the purchase, the shiplocker and backpack json files are also very useful, as they reflect the state of the shiplocker and backpack at that time. If the contents in those files are actually different from what is shown in the app and there is an event describing the purchase of the module in the journal, we can update the app based on that event.

**Comment by jixxed** [comment]
there are no events after applying an upgrade and the shiplocker file is not updated by ED. only after boarding the ship you will get another update and even then the numbers are incorrect due to a bug in ED. I will implement this if/when frontier does. for now nothing can be done about it, except for the player to relog into ED.
