### ISSUE TITLE
Future - low priority request for updates

### ISSUE THREAD

**Issue by OzDruiD** [jixxed/ed-odyssey-materials-helper#4]
Hi
Amazing tool - simpy great format\feel and suitability - thank you.
Appreciate 'New version' and download link now in the tool itself!

Just a query for update management in the long run, possibly due ot the frequent updates you are doing an amazing job of.
To update - its appears its a full download (from github exe) and reinstall.
- Is there an method to self-update or clean up this process  - eg the setup does the previous removal etc. 
- Reinstall over the to seems to be ok - no corruption noticed, but its a manual case to adjust the install path outside default
- If it is a new manual full install still required,  can it pickup old\existing install paths - defaults back to the "APPdata" type path

**Comment by jixxed** [comment]
I can look into improving the installer on the short term. There are some projects out there that work with deltas and have an auto updater like discord, so it should be possible.

**Comment by jixxed** [comment]
feature placed on the backlog: https://github.com/jixxed/ed-odyssey-materials-helper/wiki/Planned-Features and currently developing
will close this issue
