### ISSUE TITLE
Square

### ISSUE THREAD

**Issue by alexzk1** [jixxed/ed-odyssey-materials-helper#40]
Guess it is \r\n problem between Linux <--> Windows. Opening file in "text mode" should automatically handle it.
![image](https://user-images.githubusercontent.com/4589845/128119253-ab9e1bb3-3ce9-4540-9ddf-a3de6ac35dd8.png)

"Lazaurus" for example on screen.

**Comment by jixxed** [comment]
running from source is not guaranteed to be stable. there is a utf symbol indicating the material is illegal. this is not rendering on your OS. Possibly you also get this symbol after clicking on a material, marking the material as a favourite.

**Comment by alexzk1** [comment]
Then it is font. UTF is granted thing invented to be cross-OS intentionally.

**Comment by jixxed** [comment]
closing the issue as it is not an issue on ubuntu and windows, which is all I can test. If you still have the issue check for fonts with support for the symbols for your OS.

**Comment by alexzk1** [comment]
And what font do I need exactly? I see nothing in CSS file.

**Comment by jixxed** [comment]
I do not know, it probably uses the system default.
