### ISSUE TITLE
On Mouse over

### ISSUE THREAD

**Issue by FryaDuck** [jixxed/ed-odyssey-materials-helper#41]
When using mouse over popup on the left panel or Wishlist the material information (price, recipe, and location/s) only flashes up. In Overview mouse over popup stays as long as mouse is over material. It used to stay on any. See vid provided

https://user-images.githubusercontent.com/87042542/128550446-5fd10836-dd74-421e-ac43-57779a12653a.mp4

**Comment by jixxed** [comment]
indeed, I have accidentally set the showDuration instead of the showDelay to 100ms

**Comment by jixxed** [comment]
fixed in 1.38
