### ISSUE TITLE
Request: Print the Overview items

### ISSUE THREAD

**Issue by Jibsman** [jixxed/ed-odyssey-materials-helper#43]
I selected Irrelevant with stock to see what to sell to the bartender. It would be easier if I could print out the list. So I guess I'm asking for an Export List button for Overview.
THANK YOU!

**Comment by jixxed** [comment]
I don't really have a good location to place a button right now. I will keep this in mind for the future though.

**Comment by bWildcard** [comment]
I think this is a really good idea for this Program which I absolutely Love btw.

my thought would be to add an additional tab Under the Engineer tab in Ody.  Odyssey>Engineer>_____  or inside/under Bartender

**Comment by jixxed** [comment]
new option to export added under Settings
