### ISSUE TITLE
app do not update materials after name changed by frontier

### ISSUE THREAD

**Issue by Belhut** [jixxed/ed-odyssey-materials-helper#435]
Hey, So i changed the name with Frontiers, since than material helper do not update material amounts, I've deleted an app and installed again, unregister and disconnect from frontier API, tried with the restarts after each step and still the same. When i lunch the app I'm getting an error "Empty response from FC endpoint disabled. Dp you own a FC?"

**Comment by jixxed** [comment]
did you lose the Fleet Carrier(FC) with the name change? then frontier API gets disabled on start, since it is currently only used to get FC data. Make sure to select the correct commander in the bottom right. 
you can also remove your old journals if that commander no longer exists
