### ISSUE TITLE
ISSUE - Can't set fuel to max when ship has a optional internal fuel tank.

### ISSUE THREAD

**Issue by Lucaspec72** [jixxed/ed-odyssey-materials-helper#441]
I was tinkering in the app, preparing my Mandalay build, and noticed that i can't set the fuel amount to 64, even though it tells me the max is indeed 64.
![image](https://github.com/user-attachments/assets/d250ffa2-6246-43a7-b189-106d6e77b0fc)

The max seems to be the amount of the primary fuel tank.

**Comment by jixxed** [comment]
https://github.com/jixxed/ed-odyssey-materials-helper/releases/tag/2.108 WIP

**Comment by jixxed** [comment]
should be fixed in 1.112
