### ISSUE TITLE
Add License to Repository

### ISSUE THREAD

**Issue by CMDR-WDX** [jixxed/ed-odyssey-materials-helper#445]
Hey :)

At the moment it is not clear under which License the code is provided. 
Could you please add a `LICENSE` file?

@colonia-duck was planning on adding an AUR Package for edomh and needs this information

**Comment by jixxed** [comment]
I will add one. I would prefer the necessary code changes and deployment to be part of this repository though. Arch currently doesn't work properly without certain changes and I do not want to give people the suggestion it is an official release when it is not.

**Comment by CMDR-WDX** [comment]
There isn't really anything that needs to change in this Repo.

> Arch currently doesn't work properly without certain changes
I have to disagree. Arch currently works ootb building the `makeLinuxPortable` target.

We made a new build Target that is basically `makeLinuxPortable` without the Zip step. We copy the image into the target and use it for the desktop entry. But yeah… from there you can just directly invoke the file under bin on arch

**Comment by jixxed** [comment]
the edomh url scheme doesn't register correctly on Arch and also Fedora has it's issues. the registration is for working for Ubuntu, probably all Debian based OSes.
If you can fix it (I don't have Arch), then feel free to create a PR and I will add it to the github workflow so it gets released automatically.

**Comment by CMDR-WDX** [comment]
Ah. On startup I didnt select to register the handler :sweat_smile:

**Comment by dmitriigo** [comment]
I already maintain a package in [AUR](https://aur.archlinux.org/packages/ed-odyssey-materials-helper-bin). It is a repack of the portable version of the application, with a fix for the correct functioning of the edomh URL. @CMDR-WDX Could you assist me in maintaining this repository, or if you suggest an alternative option, we could manage it together?

**Comment by dmitriigo** [comment]
The portable version technically contains a binary file, not the source code, and I'm created pkgbuild from the portable version. It's strange that it doesn't work; it’s likely due to the fact that you’re using paru, while I’m using yay. I’ll need to check on that. I think it would be better to continue this discussion in the application's Discord. There’s a linux-support channel there to avoid creating off-topic discussions here.

**Comment by jixxed** [comment]
also HEAD is not appropriate to run. It will report a version that is older than HEAD and can seriously cause headaches when debugging issues. using the latest release is safer. tags also get reset if the build fails.

**Comment by jixxed** [comment]
license added
