### ISSUE TITLE
[BUG] Ship builds

### ISSUE THREAD

**Issue by Lucaspec72** [jixxed/ed-odyssey-materials-helper#446]
![image](https://github.com/user-attachments/assets/fcab1185-09d2-44eb-99f9-7f11f01f522b)
The dropdown selector for the ship builds seems to only display two builds. Would be nice for it to extend as far down as the app window allows, and maybr also add another dedicated menu that shows all the builds ?

**Comment by jixxed** [comment]
I don't make the (all) components. I know this one can be a bit quirky sometimes, but in general it works fine.
will consider a dedicated menu in the future
