### ISSUE TITLE
Launcher cannot run application

### ISSUE THREAD

**Issue by DlljsCodes** [jixxed/ed-odyssey-materials-helper#45]
After running the launcher, this error appears
![image](https://user-images.githubusercontent.com/64469452/128864544-56dab176-af54-4db5-94c3-b1d3bc3adb2d.png)
I'm still able to run the program manually by navigating to the directory specified

**Comment by jixxed** [comment]
Is there anything specific set up on your system security wise? If it is unable to find the file while it clearly exists, it indicates to me there is something preventing it from finding is, like some kind of security software or permissions.

**Comment by jixxed** [comment]
just tested the latest msi myself, appears there is some bug there.

**Comment by jixxed** [comment]
fixed in 1.40

**Comment by jixxed** [comment]
please install the latest MSI to fix your issue
