### ISSUE TITLE
Cannot login nor link Frontier account

### ISSUE THREAD

**Issue by KM-203** [jixxed/ed-odyssey-materials-helper#452]
Hello,

I have installed EDOM and I have registered to receive edom urls but I cannot link my Frontier account. EDOM cannot detect that I have logged in into the game either.

I have tried to exit and login into the game in multiple forms, I have also tried to import the edom link directly from the clipboard and stopped other ED helper applications but there is no way.

Thank you very much in advance,

**Comment by jixxed** [comment]
what operating system and browser?

**Comment by KM-203** [comment]
Hi, I've just figured out what happened thanks to the ticket opened by Logos13 in https://github.com/jixxed/ed-odyssey-materials-helper/issues/456

Turns out the program sets the journal folder directly to C:\User\...\Elite Dangerous but my journal folder was in F:\, and it has something to do with me having several drives and Windows.

Then I followed the steps that Logos13 posted and now it works perfectly.
