### ISSUE TITLE
No mc_overcharged handling

### ISSUE THREAD

**Issue by OldDregg** [jixxed/ed-odyssey-materials-helper#454]
Importing a build from Coriolis with overcharged multi-cannons results in "Unknown blueprint type: mc_overcharged"

Tested locally, and changing line 275 in HorizonsBlueprintType.java to:

```
case "weapon_overcharged",
        "mc_overcharged" -> OVERCHARGED_WEAPON;
```
              
resolves the issue. There may be a more variable way to handle it, I'm unsure why weapon_overcharged isn't picking up on it, but I had trouble figuring out how to get a copy of my edomh:// url from Coriolis, so I apologize if my suggestion is a bit crude.

**Comment by jixxed** [comment]
likely same issue as https://github.com/EDCD/coriolis/issues/776 and will be fixed in the future.

**Comment by alex-williams** [comment]
> likely same issue as [EDCD/coriolis#776](https://github.com/EDCD/coriolis/issues/776) and will be fixed in the future.

Almost certain of it, it's the next bug on my hitlist. Should be fixed this week I hope.
