### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by alexzk1** [jixxed/ed-odyssey-materials-helper#46]
Well, just possible issue, maybe nothing.

https://issues.frontierstore.net/issue-detail/39579

Happened to me twice, both times it was 5+ hours of intensive playing. Both times journal files were close to 2Mb. Both times I ran new tool ed-odyssey-materials-helper/

My current idea is, "new tool" reads file too long, so game tries to write, fails and never repeats write again.

So could you recheck read code if it gets exclusive read access which may break game and/or replace with in-ram caching of whole file then parsing it from ram (to minimize time of file access).

**Comment by alexzk1** [comment]
Ok, played many days OK without using the program. Today launched it and....Elite got broken. So chances this program breaks game by too long reading are good.
Here is my path to try, I will be trying it too couple more days.
[file_processor.txt](https://github.com/jixxed/ed-odyssey-materials-helper/files/7073382/file_processor.txt)

**Comment by jixxed** [comment]
Sounds to me Elite needs to handle file access gracefully with a retry or a writelock. Can't go with reading while data is being written to the file. The read time is already very low and only triggered after a write. Will have to see how FDev resolves the issue on their end.

**Comment by alexzk1** [comment]
> Sounds to me Elite needs to handle file access gracefully with a retry or a writelock. Can't go with reading while data is being written to the file. The read time is already very low and only triggered after a write. Will have to see how FDev resolves the issue on their end.

Yeh,
1. Other tools like EDMC python script do not break, as they do some special care.
2. you original program runs file reading in GUI thread (Platform.runLater) which may be delayed for infinite unspecified time. That just says "do it some when later when you will have time". Also order is not guaranteed. It can collect like 50 reading request lambdas then run those 50 at once. So I would revise that.

**Comment by jixxed** [comment]
Issue expired @ frontier. Still not seen any evidence, only suspicions.
