### ISSUE TITLE
Wrong active upgrades marking (minor issue)

### ISSUE THREAD

**Issue by riwarek** [jixxed/ed-odyssey-materials-helper#47]
Lets assume I've added to wish list three "Magazine Size".
Application evaluates properly amount of materials.
Problem is when I have three "Magazine Size" on whishlist and materials only for one, all three are greened like they are possible to applied. It may mislead user.

Solution: check specific amount of materials and green only proper amount of active upgrades.

**Comment by jixxed** [comment]
This is not only the case for duplicate upgrades. Any upgrade that can be crafted will turn green to indicate that the upgrade is available for crafting. For example: You have 3 Dominator suits. they are on level 1, 2 and 3. Today you decide you want to upgrade them all by 1 level. You have enough materials to upgrade from level 3 to 4. Now which of the upgrades should be green and which not? All can be equally relevant to upgrade.

There is no way of determining this unless each item has some kind of priority where none can be equal. This is way too complicated.

I feel the current system where all the materials are listed and with mouseover showing information for that specific upgrade is more than clear enough for the majority of users.

**Comment by riwarek** [comment]
Then maybe it is enough to apply it for modules, not grades?
Thing to considere is: you will not upgrade a suit to 2>3 if you have no 1>2. Then should app highlith 2>3 with green? Or maybe you should add another color "possible to upgrade but locked with current state"?
Decisions, decisions, decisions... :)
Anyway, despite all my remarks your app is "must have" for Odyssey player!

**Comment by jixxed** [comment]
It needs to apply to all or nothing, everything uses materials and behaviour needs to be clear and consistent. In the example there are 3 suits, so it is very well possible.
