### ISSUE TITLE
request: irrelevant filter to include excess materials over required amount for unlocks

### ISSUE THREAD

**Issue by danielschill** [jixxed/ed-odyssey-materials-helper#48]
change irrelevant filter to include excess materials over required amount for unlocks. for example Push, 5 is needed for the engineer unlock and then it's irrelevant.

**Comment by jixxed** [comment]
The irrelevant filter shows materials that have no known use in the game. Those are safe to be sold. Other materials you will want to save for blueprints or trading between players. It can be a configuration option for people that play exclusively solo, but it should not be the default behaviour.

**Comment by jixxed** [comment]
added in 1.42
