### ISSUE TITLE
Unable to launch app via .exe file

### ISSUE THREAD

**Issue by RDaneliya** [jixxed/ed-odyssey-materials-helper#49]
Hello, I've tried 1.41 and 1.40 releases portable version and not and I couldnt open this app simply launching .exe file, Only launching `./runtime/bin/Elite Dangerous Odyssey Materials Helper.bat` did the trick.

**Comment by jixxed** [comment]
Launches just fine here. do you perhaps have some AV or Windows blocking launching unknown exe files? Smartscreen can get in the way because the app is not digitally signed. Good that you at least have a workaround.

**Comment by RDaneliya** [comment]
I've installed app properly and tried to launch as admin. During .bat launch there was smartscreen warning but I could proceed anyway. So I believe the problem is not connected with smartscreen. If there some kind of logs are needed I can attach them

**Comment by jixxed** [comment]
There is no need to launch as admin. The exe is just a default launcher for the application to make it user friendly. I believe it just runs the bat file. There is no logging in there implemented by me. You could try to run it from the console, but as far as I know there is no logging. The only thing I can imagine interfering with launching through the exe is AV or smartscreen. Sometimes a reboot can resolve weird issues.

**Comment by RDaneliya** [comment]
Reboot didn't helped. I also found that app created new folder at C:/Users because there are troubles with encoding and it can't read cyrillic symbols 
![изображение](https://user-images.githubusercontent.com/41577858/135570800-9cfad68b-baee-4489-983d-ee8062d57cdc.png)

Maybe this can cause the problem?

**Comment by jixxed** [comment]
there have been some issues with cyrillic characters in the past, but only related to translations and reading of files. You could try and verify, by placing the application on a non-cyrillic path and copy the journal files to a non-cyrillic path(path to journal files is configurable in settings).
only the first step should potentially involve the exe though. Let me know if the first step resolves the issue, then I know where to look further.

**Comment by jixxed** [comment]
seems related to https://bugs.openjdk.java.net/browse/JDK-8205991

**Comment by jixxed** [comment]
tested myself in a cyrillic path and can confirm the issue. If the issue is gone on a non-cyrillic path, there is nothing I can do for the moment and that will be the workaround. the Java Development Kit itself will need to be fixed and updated.
