### ISSUE TITLE
Spirit of Laelaps megaship is in the incorrect location

### ISSUE THREAD

**Issue by Clockdistrict** [jixxed/ed-odyssey-materials-helper#491]
Spirit of Laelaps moved to V886 Centauri during the invasion of Shinrarta Dezhra, and has stayed there since, with zero signs of loving back to Luyten's Star.

**Comment by jixxed** [comment]
where does this show a wrong location?

**Comment by Clockdistrict** [comment]
Shows the wrong location whenever you select a Sirius techbroker module on the left side, screenshot attached while sitting in the actual system the megaship is in. Confirmed it shows the wrong location for both of the AX missile rack sizes and the pre-engineered heatsink.

![sirius module](https://github.com/user-attachments/assets/6b38cd26-0b5d-4068-88cf-8e8017f32b54)

**Comment by jixxed** [comment]
fixed in 2.129
