### ISSUE TITLE
Caustic Sink Launcher and TG Pulse Neutraliser are available for credits

### ISSUE THREAD

**Issue by Clockdistrict** [jixxed/ed-odyssey-materials-helper#492]
Both the Caustic Sink Launcher and TG Pulse Neutraliser modules are available for credits from rescue megaships, no materials required to purchase.

**Comment by jixxed** [comment]
are the blueprints no longer available at the techbroker?

**Comment by Clockdistrict** [comment]
No, they are a credit purchase now, and have been since Feb

**Comment by jixxed** [comment]
fixed in 2.129
