### ISSUE TITLE
Rescue Megaships are in wrong positions / not removed

### ISSUE THREAD

**Issue by Clockdistrict** [jixxed/ed-odyssey-materials-helper#493]
Most of the rescue megaships were destroyed when the invasion of Sol began, the only remaining rescue megaships remaining are:

- Rescue Ship Cornwallis (V886 Centauri)
- Rescue Ship Hutner (Luyten's Star)
- Allied Solace (Sun Wen)
- Imperial Sanctum (Hixkaramu)

All of the other rescue ships can be removed.

**Comment by jixxed** [comment]
updated for next release
