### ISSUE TITLE
bug: helper wont see new journal files

### ISSUE THREAD

**Issue by towingie** [jixxed/ed-odyssey-materials-helper#5]
got strange bug, tool stuck in old journal file and wont see any new, so no updates in UI (new materials etc)

![Capture](https://user-images.githubusercontent.com/3169606/121516717-39dfb780-c9f7-11eb-91b8-0a8c468c5f5d.PNG)

journal its stopped on 
[Journal.210608203049.01.log](https://github.com/jixxed/ed-odyssey-materials-helper/files/6630938/Journal.210608203049.01.log)

maybe its because no shutdown event it that file, but seems new ED client buggy enough to crash and not write such endgame events

**Comment by towingie** [comment]
i've removed buggy journal files and its worked again.
bugged file (but with shutdown event, but still not let tool pass it):
[Journal.210608202726.01.log](https://github.com/jixxed/ed-odyssey-materials-helper/files/6630929/Journal.210608202726.01.log)

**Comment by jixxed** [comment]
It watches the latest file that has the appropriate Fileheader ("Odyssey":true)
new version is incoming that no longer relies on the Journal files and will also show backpack contents
