### ISSUE TITLE
Flagged and Blocked by windows defender

### ISSUE THREAD

**Issue by IconicCard** [jixxed/ed-odyssey-materials-helper#502]
PauseEngine flagged as trojan by some AVs and new version of Material Helper is blocked by windows defender. I am unsure if it is actually a virus but older versions do not have this issue.

**Comment by jixxed** [comment]
false positive
https://www.virustotal.com/gui/url/dbb941531bea0f91de221c0ee6448f25808e4b8e133dcdbbc86dfadce6a3f48e
