### ISSUE TITLE
Selecting "Copy wishlist to clipboard" saves junk to clipboard

### ISSUE THREAD

**Issue by Jibsman** [jixxed/ed-odyssey-materials-helper#51]
This is what gets pasted to the clipboard:

U0NPUEU6dHJ1ZSxET01JTkFUT1JfU1VJVF9HUkFERV8zXzQ6dHJ1ZSxFTkdJTkVFUl9CMjp0cnVlLEVOR0lORUVSX0IzOnRydWUsRVhUUkFfQU1NT19DQVBBQ0lUWTp0cnVlLE5JR0hUX1ZJU0lPTjp0cnVlLElOQ1JFQVNFRF9TUFJJTlRfRFVSQVRJT046dHJ1ZSxFTkdJTkVFUl9DNTp0cnVlLEFSVEVNSVNfU1VJVF9HUkFERV8zXzQ6dHJ1ZSxSRURVQ0VEX1RPT0xfQkFUVEVSWV9DT05TVU1QVElPTjp0cnVl

**Comment by jixxed** [comment]
There is a new tab “+” where you can paste this string and import a wishlist. It’s wishlist sharing functionality.

**Comment by Jibsman** [comment]
OK Thanks for the info.
