### ISSUE TITLE
Locked Engineers

### ISSUE THREAD

**Issue by Modar52** [jixxed/ed-odyssey-materials-helper#58]
I a using version 1.50.00 and now all my engineers show locked.  I have unlocked most of them.  It is still reading the available materials correctly so it is finding my journal
![Screenshot 2021-12-12 135311](https://user-images.githubusercontent.com/96024631/145729228-4168737b-0baf-4316-a687-a1bb5dbe99d4.jpg)

**Comment by jixxed** [comment]
I see in the statusbar a request to login to the game, have you done that? Otherwise the event for the engineerprogress is not yet logged.
