### ISSUE TITLE
Improved Battery Capacity - Wrong Mat Number

### ISSUE THREAD

**Issue by Cloid922** [jixxed/ed-odyssey-materials-helper#65]
Maverick Suit
Electrical wiring - Currently says 10 needed for improved battery capacity mod. Actual need is 15. This is at Domino Green and a level 4 maverick suit. (If that changes anything)

Program is amazing! Thank you so much, I love it!

**Comment by jixxed** [comment]
![image](https://user-images.githubusercontent.com/14129491/149812511-1fb59fc4-cc0b-423e-b009-ebae4d94cf8e.png)
screenshot from july

can you add a screenshot? or changelog stating it has changed?

**Comment by jixxed** [comment]
You are probably confusing it with Reduced Tool Battery Consumption. Domino doesn't craft Improved Battery Capacity.

**Comment by Cloid922** [comment]
Yes, I saved a recording from the session. I'll grab a screenshot of it and
send it to you.

**Comment by Cloid922** [comment]
Welp, I feel stupid. You are correct. Sorry!

 [image: image.png]
