### ISSUE TITLE
RUS Resource localisation needs work

### ISSUE THREAD

**Issue by Habilya** [jixxed/ed-odyssey-materials-helper#68]
Hello
I'm creating this issue to keep track of issues found in RUS localisation.
To work on them later, or anyone else who wants to help can do these by all means.

-  Engineers names in game are in English, even if the game is in Russian (No need to translate them in the app)

![2022-02-05 18_15_02-Window](https://user-images.githubusercontent.com/26153731/152662227-55952e46-e815-46dc-a125-053264a9ce4d.png)

- To be reviewed
![2022-02-05 18_14_54-Window](https://user-images.githubusercontent.com/26153731/152662261-ffe59159-b9fc-4230-b800-9587755eb564.png)
(Required?)

![2022-02-05 18_11_18-Elite - Dangerous (CLIENT)](https://user-images.githubusercontent.com/26153731/152662271-73ebf9e8-601e-4e06-92a4-2bdc35d06e73.png)
(Weapon upgrade names Domino Green)

![2022-02-05 18_31_05-Elite - Dangerous (CLIENT)](https://user-images.githubusercontent.com/26153731/152662453-901976d7-c9a4-4410-b925-e39ee54f9116.png)
(Weapon upgrade names Kit Fawler)

![2022-02-05 18_14_45-Window](https://user-images.githubusercontent.com/26153731/152662289-d1d1c40f-cbb7-4820-b9a3-b5ea107061e2.png)
(Upgrade names to be reviewed for other engineers)
![2022-02-05 18_32_26-Elite - Dangerous (CLIENT)](https://user-images.githubusercontent.com/26153731/152662477-af1374df-60bc-4589-ade6-062fdd286349.png)
(suits Kit Fawler)

**Comment by jixxed** [comment]
localization moved to csv for easier editing

**Comment by jixxed** [comment]
fixed for next version
