### ISSUE TITLE
feature request: localization & overlay

### ISSUE THREAD

**Issue by towingie** [jixxed/ed-odyssey-materials-helper#7]
would be fantastic if
- add to tool localization (reflected in journal files)
- add ability to somehow overlay data in translucent mode over game to make managing of materials/data more comfort - now i'm constantly alt-tabing

**Comment by jixxed** [comment]
localization placed on the backlog: https://github.com/jixxed/ed-odyssey-materials-helper/wiki/Planned-Features

can you elaborate on translucent mode?
I feel the application is it is is too big to comfortably use in a translucent mode. I can image having some kind of blueprint pinned so you can track your progress in a translucent mode.  or maybe an overview of materials selected you want to collect.

**Comment by towingie** [comment]
i think overlay mostly need for 2 purposes:
- sellout useless materials to freeup storage slots
- place a route to place where materials can be obtained and track amounts without alt-tabing

so good solution will to have 2 modes of overlay :
- left/right sidebar with (text) list of useless materials, which will updating while selling (as soon as journal files reflect changes)
-  left/right sidebar with tracked blueprint with list of materials with amounts in backpack/storage, would be great if blueprint will give brief info where materials can be obtained.. like: `Sol, 3a` (Earth's moon)

**Comment by jixxed** [comment]
I'm closing this issue. localizations have been added in 1.20. A translucent mode is not something I will be looking into for the foreseeable future, but I will keep it in mind. I am discussing improving information on locations which may be the next big feature update.
