### ISSUE TITLE
[Win10/Elite.Dangerous.Odyssey.Materials.Helper-1.71.msi] Materials helper doesn't start

### ISSUE THREAD

**Issue by PapaLooser** [jixxed/ed-odyssey-materials-helper#73]
Steps to reproduce:
Doubleclick Elite Dangerous Odyssey Materials Helper Launcher.exe
A window 'Lauchning the application" opens for 2 seconds, then closes.

That's it.

Hadn't been using the app since a year (around 1.39/1.40), when it did work.
Now those old versions don't work either.
Any ideas what keeps it from starting?
Is there somewhere a log?

**Comment by PapaLooser** [comment]
The portable version of 1.71 does start, when being launched via
runtime/bin/Elite Dangerous Materials Helper.bat

**Comment by jixxed** [comment]
try closing all EDOMH tasks in the task manager. install the latest MSI. you can also remove the %localappdata%\odyssey-materials-helper\pref.properties file (this will reset all app settings and wishlists)
that should give you a clean start.
It is possible that jumping this many versions doesn't properly migrate all the previous settings

**Comment by PapaLooser** [comment]
Thanks for locking into it.

That didn't help.
No task where still runing, the latest MSI from two days ago was used,
removing pref.properties didn't change it either.

But I'm getting a log now.
It starts with an Access Violation:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8c1cbddc0, pid=34704, tid=2040
#
# JRE version: Java(TM) SE Runtime Environment (16.0.1+9) (build 16.0.1+9-24)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (16.0.1+9-24, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [amdxn64.dll+0x16ddc0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Djpackage.app-version=1.71 -Dapp.version=1.71 -Xmx1024M --add-exports=javafx.base/com.sun.javafx.event=org.controlsfx.controls --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Djavafx.cachedir=javafx-cache -Djpackage.app-path=F:\Spiele\EDTools\EDMaterialsHelper\program\Elite Dangerous Odyssey Materials Helper.exe -Djdk.module.main=nl.jixxed.eliteodysseymaterials nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.Main

Host: AMD Ryzen 7 3800X 8-Core Processor             , 16 cores, 31G,  Windows 10 , 64 bit Build 19041 (10.0.19041.1348)
Time: Sat Mar  5 15:24:00 2022 Mitteleuropäische Zeit elapsed time: 0.613891 seconds (0d 0h 0m 0s)

Don't put too much effort into it, the workaround with the batch file is ok for me :-)

**Comment by jixxed** [comment]
Well, based on the error it appears to be an issue with your graphics card/driver. you could try updating or a clean install with DDU(Display Driver Uninstaller)

**Comment by Vgilbert61** [comment]
Hi new to the post, similar thing is happening to me, I downloaded the 7.1 version and all it dose is show the pack man symbol chopping and then nothing, no load up just the symbol chopping and then blank, that it.
