### ISSUE TITLE
[Win11/Elite.Dangerous.Odyssey.Materials.Helper-1.71.msi] Materials helper doesn't start

### ISSUE THREAD

**Issue by Vgilbert61** [jixxed/ed-odyssey-materials-helper#74]
Hi there again I posted on some one else post (Sorry about that, New to post) about a similar problem, with the tool, I loaded the link and all it dose is have the pack man chopping and then that it, nothing come up. I try the mobile and the other links and they don't work. The MIS loads up find, but dose not work. I'm I doing something wrong? Also I have two drives one for my systems and other for games, which tools is on game drive, so question is dose the link need to be put in game program or dose it see game and just load up?

**Comment by jixxed** [comment]
this was a bug in 1.71 and was fixed in 1.72. try launching the msi(pacman) version again, it will update to 1.72.
