### ISSUE TITLE
Scaling issue - windows 

### ISSUE THREAD

**Issue by senyaak** [jixxed/ed-odyssey-materials-helper#75]
![image](https://user-images.githubusercontent.com/15360093/158673198-9b4cdcbd-b176-4694-8b57-5300775a290a.png)

I have 2k resolution and 175% interface scaling. This cause the layout at some points being broken 
Also sometimes the Popup appears at the second screen Oo do not know what cause it - but really weird

**Comment by jixxed** [comment]
You can try to play with the textsize under settings if that keeps it readable. the popup should appear on the screen where the app is open.  other than that have I not experienced such issues, but perhaps it has something to do with the scaling. I believe it is also possible to launch an application in windows with forced specified scaling.

**Comment by senyaak** [comment]
Text size do not affect it - but after some time the thing is realigned - this is just windows issue like I suggested :) 
The popup is also windows issue - but probably it is because I use windows 11 - have had really much issue with other stuff
I would say - use electron ;) there alaways a way to make the layout good :) 
PS (that doesnot mean use it for logic)

**Comment by jixxed** [comment]
can't support W11 as there are way too many issues for me to upgrade to it. may also take some time for GUI libraries to add proper support. not going to change the frontend now.
