### ISSUE TITLE
Wrong number of Power Regulators

### ISSUE THREAD

**Issue by Patsch78** [jixxed/ed-odyssey-materials-helper#8]
Hi and thanks for the great work!

Current:
In my Inventory I've got multiple piles of Power Regulators. One stack of 2 "normal" PR, 1 "normal" and 8 mission based PRs.
I used those 11 to  to upgrade my suit. It worked. After that I am having only 6 left. So PRs from every stack have been used while upgrading the suit. Some of them have different Owner IDs but the game seems not to care. 

The materials helper shows only one left (of 6). Before the suit upgrade it showed 3 (of 11). Also older Versions, at least until v1.8 of your tool (I update from 1.8 to 1.11) did not care.

Expected:
Show the total / right number of Power Regulators

Kind regards 
Patsch

![2021-06-11 00_26_22-Elite - Dangerous (CLIENT)](https://user-images.githubusercontent.com/54373982/121604921-b7cdae00-ca4b-11eb-989a-e8941c89d533.png)

![2021-06-11 00_16_57-ED Odyssey Materials Helper](https://user-images.githubusercontent.com/54373982/121604843-92d93b00-ca4b-11eb-9cf6-9b503994c1fe.jpg)

[Journal.210610211919.01.log.zip](https://github.com/jixxed/ed-odyssey-materials-helper/files/6634731/Journal.210610211919.01.log.zip)

**Comment by jixxed** [comment]
thanks for the report. fixed in 1.12!
