### ISSUE TITLE
bintray download failure

### ISSUE THREAD

**Issue by jnorthrup** [jixxed/ed-odyssey-materials-helper#87]
jim@gentoo ~/work/ed-odyssey-materials-helper $ ./gradlew install
Downloading https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.4.2!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :bootstrap:compileJava FAILED

> Task :application:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootstrap:compileJava'.
> Could not resolve all files for configuration ':bootstrap:compileClasspath'.
   > Could not resolve org.openjfx:javafx-base:18+.
     Required by:
         project :bootstrap
      > Failed to list versions for org.openjfx:javafx-base.
         > Unable to load Maven meta-data from https://dl.bintray.com/jetbrains/intellij-third-party-dependencies/org/openjfx/javafx-base/maven-metadata.xml.
            > Could not GET 'https://dl.bintray.com/jetbrains/intellij-third-party-dependencies/org/openjfx/javafx-base/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 25s
3 actionable tasks: 3 executed

**Comment by jnorthrup** [comment]
this link may be relevant 

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by jixxed** [comment]
the bintray repo is probably no longer needed and can be removed. you also probably don't need the bootstrap project if you are running from source.

**Comment by jnorthrup** [comment]
@jixxed was this issue closed in response to a change that makes `gradle install` work?  im not sure how one runs from source, maybe a line in the README or a wiki entry perhaps?

**Comment by jixxed** [comment]
The issue was closed based on the description you gave. the bintray repo has been removed.
you can find releases here: https://github.com/jixxed/ed-odyssey-materials-helper/releases
I don't know what you are trying to achieve by running from source? The discord is a good place to help you get setup for whatever you are trying to achieve.
