### ISSUE TITLE
Incorrect Barter Values

### ISSUE THREAD

**Issue by NovitiateSage** [jixxed/ed-odyssey-materials-helper#89]
Barter Values for:

Memory Chip 5/3, Micro Hydraulics 4/2, Micro Thrusters 7/4.

Are incorrect, it seems they were swapped with each other (Fdev rebalancing?)

Bartender asks 4 value for Memory Chip, 7 value for Micro Hydraulics, 5 value for Micro Thrusters. The thrusters themselves are worth 3 value. I can't see the others, because I don't have any on me to make the bartender display their sell value.

 These are the only discrepancies I was able to find.

![20220920155333_1](https://user-images.githubusercontent.com/110263944/191163828-dbbe4568-d19f-43d6-b20a-b69e274677fe.jpg)

**Comment by jixxed** [comment]
Appears some old labels were still being used there. bartender tab had the correct values. I remember there was some rebalancing a long time ago. thnx for the report!

**Comment by jixxed** [comment]
discovered some other issues too
microelectrode sell 8 > 9
microthruster sell 4 > 3
weaponcomponent sell 9 > 10
graphene sell 12 > 13
same issue in the credit values
fixed for next release
