### ISSUE TITLE
feature request: collapse/hide empty categories of material while using search

### ISSUE THREAD

**Issue by towingie** [jixxed/ed-odyssey-materials-helper#9]
if i'd enter in search something specific enough, for example something from Data, other categories shown as empty which make not very comfort to use app (need to scroll right inside window to category, especially if window not so big).

Would be great to hide/collapse empty categories inside window while nothing found by search criteria

as another trick to make search more comfortable to use, make a small delay(half second) after character entered in search field and firing search, to app not try hurry search typed name of material and get laggy while i quickly typing name

**Comment by towingie** [comment]
just thought, would be great to show bartender price for materials

**Comment by jixxed** [comment]
category collapsing -> the application is made with fullHD @ 100% scaling in mind. You should not need to scroll at this configuration. Are you playing at something lower? Collapsing will require some rework and is low on the priorities list.

The half second delay was implemented when the feature was developed. haven't you noticed?

things like localization, prices, locations will take some time until I have some overview.

**Comment by towingie** [comment]
1680x1050 :-)

> The half second delay was implemented when the feature was developed. haven't you noticed?
nope :-/

**Comment by towingie** [comment]
double checked. delay indeed implemented :-)

**Comment by jixxed** [comment]
new layout introduced in 1.16!
