### ISSUE TITLE
Feature request: import material list/checklist from EDSY

### ISSUE THREAD

**Issue by uxlapogi** [jixxed/ed-odyssey-materials-helper#90]
Hi,

when I use the EDSY retrofit report under ANALYSIS I get a handy checklist of what to change as well as list of all materials needed to upgrade from my current build to my target build.
If possible I'd like to be able to import this as a wishlist.

Thanks!

Here's an example of the two lists as generated by EDSY:

---Checklist:

Build Module Act Details
Lazy Mule 0I Heat Sink Launcher Buy 0,0% discount
Lazy Mule 4A Power Plant Eng Low Emissions G1 x1
Lazy Mule 4A Power Plant Eng Low Emissions G2 x1.5
Lazy Mule 4A Power Plant Eng Low Emissions G3 x2.5
Lazy Mule 4A Power Plant Eng Low Emissions G4 x4
Lazy Mule 4A Power Plant Exp Stripped Down
Lazy Mule 6A Frame Shift Drive Eng Increased Range G5 x7
Lazy Mule 5D Power Distributor Eng Charge Enhanced G1 x1
Lazy Mule 5D Power Distributor Eng Charge Enhanced G2 x1.5
Lazy Mule 5D Power Distributor Eng Charge Enhanced G3 x2.5
Lazy Mule 4D Sensors Eng Light Weight G1 x1
Lazy Mule 4D Sensors Eng Light Weight G2 x1.5
Lazy Mule 4D Sensors Eng Light Weight G3 x2.5

---Materials list:

Item Type Lvl Qty
Credits 3.500
Arsenic Raw G2 7
Chemical Distillery Mfc G3 3
Chemical Manipulators Mfc G4 7
Chemical Processors Mfc G2 2
Conductive Ceramics Mfc G3 3
Datamined Wake Exceptions Enc G5 7
Germanium Raw G2 4
Grid Resistors Mfc G1 8
Heat Exchangers Mfc G3 3
Heat Vanes Mfc G4 4
Iron Raw G1 5
Irregular Emission Data Enc G2 4
Manganese Raw G2 4
Modified Consumer Firmware Enc G2 3
Phosphorus Raw G1 1
Proto Light Alloys Mfc G4 1
Salvaged Alloys Mfc G1 4
Specialised Legacy Firmware Enc G1 3
Unexpected Emission Data Enc G3 4
Vanadium Raw G2 3

Edit:
P.S. I found the buttons to export the wishlist but I cannot find a way to reimport it. Am I missing something?

**Comment by jixxed** [comment]
The wishlist and the build are not linked together. We chose to implement for the initial version only the shipyard/outfitting tabs.
EDSY communicates only the blueprints to the app, so you can't construct a ship back from it(the app only known blueprints, not modules). The Analysis tab has rolls per grade configuration that is different from the app(also works with decimals, while the app does not). This would be confusing to the user. With enough interest we will implement it also for Analysis tab.

**Comment by uxlapogi** [comment]
Had to read your answer several times, but I finally understand now. :D

I only had the video from 'The Buur Pit' to get started and found no other documentation. I found the export function on the OUTFITTING tab of EDSY now and was able to import an EDSY build which is awesome.

Just to clarify:
Of course the EDSY build and the EDOMH wishlist are not linked. What I meant with reimport was, currently I can export the EDOMH wishlist as a .TXT file in EDOMH but once I have that .TXT file I cannot import it back into EDOMH (for example on another device or as backup).

I think the big advantage of the analysis tab is that you get accurate numbers for the materials you need for the delta between an existing build and a target build.

**Comment by jixxed** [comment]
There is someone currently working on videos for the app that should come out in the coming weeks. 
You can copy your wishlist to clipboard, which will create a link you can share. clicking that link will import that wishlist.

**Comment by jixxed** [comment]
the video: https://youtu.be/8EXOeB074Zw

**Comment by uxlapogi** [comment]
Awesome! Thank you!

**Comment by jixxed** [comment]
I am closing this issue. with enough interest it will eventually be added to EDSY Retrofit. keeping track of it on the discord
