### ISSUE TITLE
Error Language Spanish/French in Commodities

### ISSUE THREAD

**Issue by VincentDob** [jixxed/ed-odyssey-materials-helper#91]
Hello,
First of all, congratulations for this tool!
There is a language error in the display of the goods data for the French language. It is the Spanish language that is displayed in Horizons>Commodities:
![image](https://user-images.githubusercontent.com/45484207/192108068-275da301-f823-4ce8-8a78-6a8783d67fd0.png)
![image](https://user-images.githubusercontent.com/45484207/192108077-ccc00335-60dc-4487-8eea-46b29924b21f.png)

Inversely for when choosing the espanol language
![image](https://user-images.githubusercontent.com/45484207/192108096-20e117f6-be7a-4ca4-bede-005a4089dc07.png)
![image](https://user-images.githubusercontent.com/45484207/192108133-3d050da2-6004-4951-9a6a-db0ed040f014.png)

**Comment by jixxed** [comment]
thnx for reporting, will get it fixed for the next release

**Comment by jixxed** [comment]
fixed in 1.92
