### ISSUE TITLE
Elite Dangerous Odyssey Materials Helper wont launch.

### ISSUE THREAD

**Issue by britrb** [jixxed/ed-odyssey-materials-helper#93]
First it comes up with "Failed to launch JVM" and then when I click ok on that it comes up with "Elite Dangerous Odyssey Materials Helper.exe Child process exited with code 1"

Help? What do I do? Have tried uninstalling and reinstalling, turning it off and on again. This is the extent of my knowledge.. Please help, I'm clueless without it!!

Thanks for a greatly useful app (It really is incredibly helpful!)
Brian :)

**Comment by jixxed** [comment]
head to the discord for support: https://discord.gg/M8Rgz4AmmA

**Comment by britrb** [comment]
Thank you, I'm there now - Willis.
