### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by babydocno** [jixxed/ed-odyssey-materials-helper#96]
Installed 1.94 yesterday.  Today, antivirus tells me that SONAR.ProcHijack!g43 was detected and disabled the program.  Has anyone else had this issue?

**Comment by jixxed** [comment]
sounds like a false positive: https://www.virustotal.com/gui/url/a89ef620fb13c742447a90ccfc9c75443c330aa82bf1892a319f43b10f6290b6?nocache=1

**Comment by babydocno** [comment]
Thanks.  I figured that but just wanted to check before allowing it through.  Just weird that it happened after updating to 1.94. 


Sent from Yahoo Mail for iPhone


On Monday, October 10, 2022, 12:06 AM, jixxed ***@***.***> wrote:




sounds like a false positive: https://www.virustotal.com/gui/url/a89ef620fb13c742447a90ccfc9c75443c330aa82bf1892a319f43b10f6290b6?nocache=1

**Comment by jixxed** [comment]
There was some resilience added in 1.94 to prevent losing all preferences and wishlists. The app could write an empty file in case of a sudden termination. It now writes everything to a temp file and then copies/overwrites it to the original preferences file. This overwrite might be what Norton sees as a virus/malware as those also tend to overwrite things.
