### ISSUE TITLE
Can't register (edomh://) with portable version or use .deb on Arch Linux

### ISSUE THREAD

**Issue by ThornedRose** [jixxed/ed-odyssey-materials-helper#97]
First, I just want to say thanks so much for having a Linux version!

I have tried running both the portable version and the .deb package (via debtap package converter).

With the portable version, I can't get the app to register edomh:// links. Clicking "register" doesn't actually do anything. And I get these errors in the terminal:
`
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'`

`mimeType "x-scheme-handler/edomh" not found`

If I ignore that, then trying to connect my Frontier account just results in the browser coming up with "Open xdg-open"

So I switched tactic and tried converting to the .deb package to something Arch can install (via debtap) but I get the following errors doing that:

```
*** Creation of .PKGINFO file in progress. It may take a few minutes, please wait...
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /

Warning: These provisions (provides =   fields) could not be translated into Arch Linux packages names:
elite-dangerous-odyssey-materials-helper
```

And trying install the above resultant packagge:

```
:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 java-environment-common-...     2.5 KiB  22.7 KiB/s 00:00 [-------------------------------] 100%
 jre8-openjdk-8.345.u01-1...   178.4 KiB  1405 KiB/s 00:00 [-------------------------------] 100%
 jre8-openjdk-headless-8....    28.8 MiB  59.1 MiB/s 00:00 [-------------------------------] 100%
 jdk8-openjdk-8.345.u01-1...     8.6 MiB  16.1 MiB/s 00:01 [-------------------------------] 100%
 Total (4/4)                    37.6 MiB  69.6 MiB/s 00:01 [-------------------------------] 100%
(5/5) checking keys in keyring                             [-------------------------------] 100%
(4/5) checking package integrity                           [-------------------------------] 100%
(4/5) loading package files                                [-------------------------------] 100%
(5/5) checking for file conflicts                          [-------------------------------] 100%
(5/5) checking available disk space                        [-------------------------------] 100%
:: Processing package changes...
(1/5) installing java-environment-common                   [-------------------------------] 100%
(2/5) installing jre8-openjdk-headless                     [-------------------------------] 100%
Default Java environment is already set to 'java-18-openjdk'
See 'archlinux-java help' to change it
Optional dependencies for jre8-openjdk-headless
    java-rhino: for some JavaScript support
(3/5) installing jre8-openjdk                              [-------------------------------] 100%
Default Java environment is already set to 'java-18-openjdk'
See 'archlinux-java help' to change it
when you use a non-reparenting window manager,
set _JAVA_AWT_WM_NONREPARENTING=1 in /etc/profile.d/jre.sh
Optional dependencies for jre8-openjdk
    icedtea-web: web browser plugin + Java Web Start
    alsa-lib: for basic sound support [installed]
    gtk2: for the Gtk+ look and feel - desktop usage [installed]
    java8-openjfx: for JavaFX GUI components support
(4/5) installing jdk8-openjdk                              [-------------------------------] 100%
Default Java environment is already set to 'java-18-openjdk'
See 'archlinux-java help' to change it
/tmp/alpm_GPakk0/.INSTALL: line 3: syntax error near unexpected token `}'
/tmp/alpm_GPakk0/.INSTALL: line 3: `}'
/usr/bin/bash: line 1: pre_install: command not found
error: command failed to execute correctly
(5/5) installing elite-dangerous-odyssey-materials-helper  [-------------------------------] 100%
/tmp/alpm_SFpb0a/.INSTALL: line 3: syntax error near unexpected token `}'
/tmp/alpm_SFpb0a/.INSTALL: line 3: `}'
/usr/bin/bash: line 1: post_install: command not found
error: command failed to execute correctly
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```
Not sure where to go from here. I've tried what I can but I'm at the limits of my Cognitive Impairment so help would be much appreciated! :)

**Comment by jixxed** [comment]
[Register application] creates a file in /.local/share/applications/edomh.desktop
this links the edomh:// urls to the app.
If your distro works differently, you should try to figure out how to link it. it may be that the file has to be placed in a different location.

**Comment by ThornedRose** [comment]
> [Register application] creates a file in /.local/share/applications/edomh.desktop 

I have no .edomh file created in ~/.local/share/applications. Arch isn't any different from other distros in that respect. There's other .desktops in there and EDMC, for example, sits in ~/.local/share/
I'll try manually creating the .desktop file and see if that fixes it. :)

**Comment by jixxed** [comment]
https://github.com/jixxed/ed-odyssey-materials-helper/blob/master/application/src/main/java/nl/jixxed/eliteodysseymaterials/service/RegistryService.java Contains the contents for the file and also some commands that are executed with this file to register the handling.

**Comment by jixxed** [comment]
@ThornedRose have you been able to fix it?

**Comment by ThornedRose** [comment]
> @ThornedRose have you been able to fix it?

Sorry, been busy with volunteer work and kids birthdays. 

I manually added a custom .desktop file. Even after that, I still had some issues with MIME type not being associated correctly. Unfortunately, with being so busy and having Memory Impairment I don't know what exactly I did to fix that. Possibly updating the MIME cache. It works now at any rate. My spouse (also on Arch) had the similar problem. He did have a edomh.desktop file show up in ~/.local/share/applications but edomh:// links still didn't associate with the app. He fiddled and it started working.

For me, it says it's connected with my Frontier account. I haven't had time to actually test that's the case and not sure what I need to look for to do that.

I do have this box popping up ("Empty response from FC endpoint"). Not sure if that's related or something else.

![Screenshot_20221011_191450](https://user-images.githubusercontent.com/239386/195302833-50905082-f432-42f8-a1fc-ea8441dba42e.png)

**Comment by jixxed** [comment]
There were some commands executed after adding the file to register it properly. A system reboot would probably have the same effect. 
Linking your frontier account is currently only used for fleetcarrier stock and orders. if you do not own a FC, the response will be empty and disable the integration while the app is being used. The message should only pop up on launch of the app, but you can also unlink your account if you desire. 
In the future I like to add additional information from the API to it, like owned suits and weapons, but Frontier never updated it since the release of Odyssey and the information is still missing.

**Comment by jimmon89** [comment]
i had downloaded the source for the most recent release version (2.14) [6c7b6b4799c3aefb4621073691da7e344523224f](https://github.com/jixxed/ed-odyssey-materials-helper/commit/6c7b6b4799c3aefb4621073691da7e344523224f) because the portable linux version refused to run, and noticed that it refused to "register" the application, let alone create the .desktop file.
even when i manually created the proper ~/.local/share/applications/edomh.desktop file, it still refused to register.
but when i commented out everything in the function `isRegistered()` and then make it always return true
the association to edomh:// works perfectly
it works good enough for me, but i thought you should be aware that it's still a problem

**Comment by jixxed** [comment]
If you run from source it will not work. only the compiled versions can register. running from source runs on the java process, while the compiled version runs on it's own.
You are also on 2.13, forgot to push 2.14, just did it. although you are probably seeing dev. a lot of features are disabled in dev.
running from source is absolutely not the intended way to run the program.

**Comment by jimmon89** [comment]
that makes sense, i appreciate the fast response

**Comment by jixxed** [comment]
the files are also present in the zip? Not sure what caused it for you to miss them.
![image](https://user-images.githubusercontent.com/14129491/215365590-7bccc0c7-1080-4b49-9e2d-88ad507a1aef.png)

**Comment by jimmon89** [comment]
The file you have there more than twice the size of the one on the release page
Yours is just over 280MiB
The one on the release page is just over 96 MiB

**Comment by jimmon89** [comment]
Very odd...
Had to download it on my phone (too lazy to fire my computer back up tonight XD)
And when I unzipped it there, the files are 100% there.
I'll have to take a look tomorrow, but I'm calling a 50/50 on whether kde's archive tool front end going completely stupid,
Or if I'm the one who went completely stupid.
But either way, the problem is on my end.
My apologies
(Btw loving the app, user error aside)
