### ISSUE TITLE
Request: Add a hotkey to bring the app window forward

### ISSUE THREAD

**Issue by c0dejunKie** [jixxed/ed-odyssey-materials-helper#98]
When playing I have several programs running in the background(voice attack, spotify, chrome, etc..) and I am always selecting the wrong app when trying to alt-tab to your app and back to the game window so I would like to make a request to have the ability to set a hotkey in order to bring the app window forward so that it can be viewed quickly while in game and second press to move the app window back to the game window quickly, similar to alt-tab but just for the app. Adding this hotkey will also allow users that use voice attack to set a voice command to set the app window to active/background as well. 

On a side note, another feature that I feel would compliment the feature I requested above would be to allow the app to be minimized to the notification tray when the window is not active.

Thank you for your time and effort.

**Comment by jixxed** [comment]
ever tried multidesktop so you can switch with CTRL + WIN + ARROW?
just use WIN + TAB and drag the app to the next desktop

**Comment by bWildcard** [comment]
Hold Alt while pressing Tab
