### ISSUE TITLE
AR does not work

### ISSUE THREAD

**Issue by CaptainADK** [jixxed/ed-odyssey-materials-helper#99]
Hello,

I think I have a problem with the augmented reality feature because it doesn't appear even though I have activated it, have a Windows 64-bit system, the game is in frameless mode and I also have the Microsoft Visual C++ driver installed. My guess is that it might not work because I am using Windows 11. I have tried many other things like switching between windowed and frameless mode, changing the colours of the AR feature, etc. Now I've been working on it for 2 days, but unfortunately it still doesn't work. I play on a laptop, which has an integrated graphics card and a dedicated graphics card, but both ED and Material Helper run on the dedicated one. Oh and sometimes it appears around a single piece of data that it is irrelevant. Unfortunately, this happens very rarely. Maybe someone can help me 

Greetings
CaptainADK

**Comment by jixxed** [comment]
Given that it sometimes appears, the feature seems to be working fine. Do you have custom HUD colors enabled? Custom colors with too little contrast can prevent proper detection. The feature is confirmed to be working fine on W11. to get more interactive support, you can also head over to the discord.

**Comment by CaptainADK** [comment]
If you mean the hud colours ingame, i haven't changed anything. If you mean the hud colours from the AR feature, they are on the default settings anyway. Then I'll go to the Discord server, it will probably be easier with the help there.

**Comment by CaptainADK** [comment]
So for people who are going to look at this and have the same problem. You just have to make sure that the in-game language and the OCR language are the same in the settings for the AR features in Material Helper.
